OGRE-Next: Ogre::Radian Class Reference
Ogre::Radian Class Reference
Core » Math
Wrapper class which indicates a given angle value is in Radians.
#include <OgreMath.h>
Public Member Functions
Radian (const Degree &d)
Radian (Real r=0)
bool operator!= (const Radian &r) const
Radian operator* (const Radian &f) const
Radian operator* (Real f) const
Radian & operator*= (Real f)
const Radian & operator+ () const
Radian operator+ (const Degree &d) const
Radian operator+ (const Radian &r) const
Radian & operator+= (const Degree &d)
Radian & operator+= (const Radian &r)
Radian operator- () const
Radian operator- (const Degree &d) const
Radian operator- (const Radian &r) const
Radian & operator-= (const Degree &d)
Radian & operator-= (const Radian &r)
Radian operator/ (Real f) const
Radian & operator/= (Real f)
bool operator< (const Radian &r) const
bool operator<= (const Radian &r) const
Radian & operator= (const Degree &d)
Radian & operator= (const Real &f)
bool operator== (const Radian &r) const
bool operator> (const Radian &r) const
bool operator>= (const Radian &r) const
Real valueAngleUnits () const
Real valueDegrees () const
Real valueRadians () const
Detailed Description
Wrapper class which indicates a given angle value is in Radians.
Remarks
Radian values are interchangeable with Degree values, and conversions will be done automatically between them.
Constructor & Destructor Documentation
Radian()
Ogre::Radian::Radian (Real r = 0) inline explicit
Member Function Documentation
operator!=()
bool Ogre::Radian::operator!= (const Radian & r) const inline
operator*() [1/2]
Radian Ogre::Radian::operator* (const Radian & f) const inline
operator*() [2/2]
Radian Ogre::Radian::operator* (Real f) const inline
operator*=()
Radian & Ogre::Radian::operator*= (Real f) inline
operator+() [1/2]
const Radian & Ogre::Radian::operator+ () const inline
operator+() [2/2]
Radian Ogre::Radian::operator+ (const Radian & r) const inline
operator+=()
Radian & Ogre::Radian::operator+= (const Radian & r) inline
operator-() [1/2]
Radian Ogre::Radian::operator- () const inline
operator-() [2/2]
Radian Ogre::Radian::operator- (const Radian & r) const inline
operator-=()
Radian & Ogre::Radian::operator-= (const Radian & r) inline
operator/()
Radian Ogre::Radian::operator/ (Real f) const inline
operator/=()
Radian & Ogre::Radian::operator/= (Real f) inline
operator<()
bool Ogre::Radian::operator< (const Radian & r) const inline
operator<=()
bool Ogre::Radian::operator<= (const Radian & r) const inline
operator=()
Radian & Ogre::Radian::operator= (const Real & f) inline
operator==()
bool Ogre::Radian::operator== (const Radian & r) const inline
operator>()
bool Ogre::Radian::operator> (const Radian & r) const inline
operator>=()
bool Ogre::Radian::operator>= (const Radian & r) const inline
valueRadians()
Real Ogre::Radian::valueRadians () const inline
Referenced by Ogre::Math::Abs(), Ogre::Math::Cos(), Ogre::Vector3::directionEquals(), Ogre::operator*(), Ogre::operator/(), Ogre::Math::Sign(), Ogre::Math::Sin(), Ogre::Math::Sqrt(), and Ogre::Math::Tan().
The documentation for this class was generated from the following file:
OgreMath.h