OGRE-Next: Ogre::v1::HardwareBuffer Class Reference
Ogre::v1::HardwareBuffer Class Reference abstract
Core » RenderSystem
Abstract class defining common features of hardware buffers.
#include <OgreHardwareBuffer.h>
Public Types
enum LockOptions {
HBL_NORMAL , HBL_DISCARD , HBL_READ_ONLY , HBL_NO_OVERWRITE ,
HBL_WRITE_ONLY
}
Locking options.
enum Usage {
HBU_STATIC = 1 , HBU_DYNAMIC = 2 , HBU_WRITE_ONLY = 4 , HBU_DISCARDABLE = 8 ,
HBU_STATIC_WRITE_ONLY = 5 , HBU_DYNAMIC_WRITE_ONLY = 6 , HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
HardwareBuffer (Usage usage, bool systemMemory, bool useShadowBuffer)
Constructor, to be called by HardwareBufferManager only.
virtual ~HardwareBuffer ()
virtual void _updateFromShadow ()
Updates the real buffer from the shadow buffer, if required.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void * getRenderSystemData ()
An internal function that should be used only by a render system for internal use.
size_t getSizeInBytes () const
Returns the size of this buffer in bytes.
Usage getUsage () const
Returns the Usage flags with which this buffer was created.
bool hasShadowBuffer () const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked () const
Returns whether or not this buffer is currently locked.
bool isSystemMemory () const
Returns whether this buffer is held in system memory.
void * lock (LockOptions options)
Lock the entire buffer for (potentially) reading / writing.
virtual void * lock (size_t offset, size_t length, LockOptions options)
Lock the buffer for (potentially) reading / writing.
virtual void readData (size_t offset, size_t length, void *pDest)=0
Reads data from the buffer and places it in the memory pointed to by pDest.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
virtual void unlock ()
Releases the lock on this buffer.
virtual void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)=0
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Detailed Description
Abstract class defining common features of hardware buffers.
Remarks
A 'hardware buffer' is any area of memory held outside of core system ram, and in our case refers mostly to video ram, although in theory this class could be used with other memory areas such as sound card memory, custom coprocessor memory etc.
This reflects the fact that memory held outside of main system RAM must be interacted with in a more formal fashion in order to promote cooperative and optimal usage of the buffers between the various processing units which manipulate them.
This abstract class defines the core interface which is common to all buffers, whether it be vertex buffers, index buffers, texture memory or framebuffer memory etc.
Buffers have the ability to be 'shadowed' in system memory, this is because the kinds of access allowed on hardware buffers is not always as flexible as that allowed for areas of system memory - for example it is often either impossible, or extremely undesirable from a performance standpoint to read from a hardware buffer; when writing to hardware buffers, you should also write every byte and do it sequentially. In situations where this is too restrictive, it is possible to create a hardware, write-only buffer (the most efficient kind) and to back it with a system memory 'shadow' copy which can be read and updated arbitrarily. Ogre handles synchronising this buffer with the real hardware buffer (which should still be created with the HBU_DYNAMIC flag if you intend to update it very frequently). Whilst this approach does have its own costs, such as increased memory overhead, these costs can often be outweighed by the performance benefits of using a more hardware efficient buffer. You should look for the 'useShadowBuffer' parameter on the creation methods used to create the buffer of the type you require (see HardwareBufferManager) to enable this feature.
Member Enumeration Documentation
LockOptions
enum Ogre::v1::HardwareBuffer::LockOptions
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
Usage
enum Ogre::v1::HardwareBuffer::Usage
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Constructor & Destructor Documentation
HardwareBuffer()
Ogre::v1::HardwareBuffer::HardwareBuffer (Usage usage, bool systemMemory, bool useShadowBuffer) inline
Constructor, to be called by HardwareBufferManager only.
~HardwareBuffer()
virtual Ogre::v1::HardwareBuffer::~HardwareBuffer () virtual
Member Function Documentation
_updateFromShadow()
virtual void Ogre::v1::HardwareBuffer::_updateFromShadow () inline virtual
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
copyData() [1/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References getSizeInBytes().
copyData() [2/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) inline virtual
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
References lock(), and unlock().
getRenderSystemData()
virtual void * Ogre::v1::HardwareBuffer::getRenderSystemData () inline virtual
An internal function that should be used only by a render system for internal use.
Reimplemented in Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
getSizeInBytes()
size_t Ogre::v1::HardwareBuffer::getSizeInBytes () const inline
Returns the size of this buffer in bytes.
Referenced by copyData().
getUsage()
Usage Ogre::v1::HardwareBuffer::getUsage () const inline
Returns the Usage flags with which this buffer was created.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
hasShadowBuffer()
bool Ogre::v1::HardwareBuffer::hasShadowBuffer () const inline
Returns whether this buffer has a system memory shadow for quicker reading.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
isLocked()
bool Ogre::v1::HardwareBuffer::isLocked () const inline
Returns whether or not this buffer is currently locked.
References isLocked().
Referenced by isLocked(), and unlock().
isSystemMemory()
bool Ogre::v1::HardwareBuffer::isSystemMemory () const inline
Returns whether this buffer is held in system memory.
lock() [1/2]
void * Ogre::v1::HardwareBuffer::lock (LockOptions options) inline
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
References lock().
Referenced by lock().
lock() [2/2]
virtual void * Ogre::v1::HardwareBuffer::lock (size_t offset, size_t length, LockOptions options) inline virtual
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns
Pointer to the locked memory
Reimplemented in Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, and Ogre::v1::GL3PlusDefaultHardwareIndexBuffer.
References lock(), and OGRE_EXCEPT.
Referenced by copyData(), Ogre::v1::HardwareBufferLockGuard::lock(), Ogre::v1::HardwareBufferLockGuard::lock(), and lock().
readData()
virtual void Ogre::v1::HardwareBuffer::readData (size_t offset, size_t length, void * pDest) pure virtual
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implemented in Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::D3D11HardwareBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
suppressHardwareUpdate()
void Ogre::v1::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline
Pass true to suppress hardware upload of shadow buffer changes.
unlock()
virtual void Ogre::v1::HardwareBuffer::unlock () inline virtual
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented in Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, and Ogre::v1::GL3PlusDefaultHardwareIndexBuffer.
References isLocked(), and unlock().
Referenced by copyData(), unlock(), and Ogre::v1::HardwareBufferLockGuard::unlock().
writeData()
virtual void Ogre::v1::HardwareBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) pure virtual
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implemented in Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::D3D11HardwareBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
The documentation for this class was generated from the following file:
OgreHardwareBuffer.h