OGRE-Next: Ogre::Lod0Stripifier Class Reference
Ogre::Lod0Stripifier Class Reference
#include <OgreLod0Stripifier.h>
Public Member Functions
Lod0Stripifier ()
~Lod0Stripifier ()
bool StripLod0Vertices (const v1::MeshPtr &mesh, bool stableVertexOrder=false)
Constructor & Destructor Documentation
Lod0Stripifier()
Ogre::Lod0Stripifier::Lod0Stripifier () inline
~Lod0Stripifier()
Ogre::Lod0Stripifier::~Lod0Stripifier () inline
Member Function Documentation
StripLod0Vertices()
bool Ogre::Lod0Stripifier::StripLod0Vertices (const v1::MeshPtr & mesh, bool stableVertexOrder = false) inline
References Ogre::Mesh::_setLodInfo(), Ogre::v1::AnimationTrack::getHandle(), Ogre::VectorIteratorWrapper< T, IteratorType >::getNext(), Ogre::MapIteratorWrapper< T, IteratorType >::getNext(), Ogre::Mesh::getNumLodLevels(), Ogre::Mesh::getNumSubMeshes(), Ogre::Mesh::getSubMesh(), Ogre::v1::Pose::getTarget(), Ogre::v1::Animation::getVertexTrackIterator(), Ogre::IteratorWrapper< T, IteratorType, ValType >::hasMoreElements(), Ogre::v1::SubMesh::indexData, Ogre::v1::SubMesh::mLodFaceList, OGRE_DELETE, Ogre::VerticesRemapInfo::performBoneAssignmentRemap(), Ogre::VerticesRemapInfo::performIndexDataRemap(), Ogre::VerticesRemapInfo::performVertexDataRemap(), Ogre::Mesh::prepareForShadowMapping(), Ogre::v1::SubMesh::useSharedVertices, Ogre::v1::SubMesh::vertexData, and Ogre::VpNormal.
The documentation for this class was generated from the following file:
OgreLod0Stripifier.h