OGRE-Next: Ogre::AtomicScalar< T > Class Template Reference
Ogre::AtomicScalar< T > Class Template Reference
Core » General
#include <OgreAtomicScalar.h>
Public Member Functions
AtomicScalar ()
AtomicScalar (const AtomicScalar< T > &cousin)
AtomicScalar (const T &initial)
bool cas (const T &old, const T &nu)
T get () const
T operator++ ()
T operator++ (int)
T operator+= (const T &add)
T operator-- ()
T operator-- (int)
T operator-= (const T &sub)
void operator= (const AtomicScalar< T > &cousin)
void set (const T &v)
Constructor & Destructor Documentation
AtomicScalar() [1/3]
template<class T > Ogre::AtomicScalar< T >::AtomicScalar (const T & initial) inline
AtomicScalar() [2/3]
template<class T > Ogre::AtomicScalar< T >::AtomicScalar (const AtomicScalar< T > & cousin) inline
AtomicScalar() [3/3]
template<class T > Ogre::AtomicScalar< T >::AtomicScalar () inline
Member Function Documentation
cas()
template<class T > bool Ogre::AtomicScalar< T >::cas (const T & old, const T & nu) inline
References OGRE_LOCK_AUTO_MUTEX.
Referenced by Ogre::Resource::markForReload().
get()
template<class T > T Ogre::AtomicScalar< T >::get () const inline
Referenced by Ogre::Resource::getLoadingState(), Ogre::Resource::isLoaded(), Ogre::Resource::isLoading(), and Ogre::Resource::isPrepared().
operator++() [1/2]
template<class T > T Ogre::AtomicScalar< T >::operator++ () inline
References OGRE_LOCK_AUTO_MUTEX.
operator++() [2/2]
template<class T > T Ogre::AtomicScalar< T >::operator++ (int) inline
References OGRE_LOCK_AUTO_MUTEX.
operator+=()
template<class T > T Ogre::AtomicScalar< T >::operator+= (const T & add) inline
References OGRE_LOCK_AUTO_MUTEX.
operator--() [1/2]
template<class T > T Ogre::AtomicScalar< T >::operator-- () inline
References OGRE_LOCK_AUTO_MUTEX.
operator--() [2/2]
template<class T > T Ogre::AtomicScalar< T >::operator-- (int) inline
References OGRE_LOCK_AUTO_MUTEX.
operator-=()
template<class T > T Ogre::AtomicScalar< T >::operator-= (const T & sub) inline
References OGRE_LOCK_AUTO_MUTEX.
operator=()
template<class T > void Ogre::AtomicScalar< T >::operator= (const AtomicScalar< T > & cousin) inline
set()
template<class T > void Ogre::AtomicScalar< T >::set (const T & v) inline
Referenced by Ogre::Resource::setToLoaded().
The documentation for this class was generated from the following file:
OgreAtomicScalar.h