OGRE: Ogre::LinearResampler_Byte< channels > Struct Template Reference
Ogre::LinearResampler_Byte< channels > Struct Template Reference
Core » Image
#include <OgreImageResampler.h>
Static Public Member Functions
static void scale (const TextureBox &src, PixelFormatGpu srcFormat, const TextureBox &dst, PixelFormatGpu dstFormat)
Member Function Documentation
scale()
template<unsigned int channels> static void Ogre::LinearResampler_Byte< channels >::scale (const TextureBox & src, PixelFormatGpu srcFormat, const TextureBox & dst, PixelFormatGpu dstFormat) inline static
References Ogre::TextureBox::atFromOffsettedOrigin(), Ogre::TextureBox::bytesPerRow, Ogre::TextureBox::getDepthOrSlices(), Ogre::TextureBox::height, Ogre::LinearResampler::scale(), and Ogre::TextureBox::width.
The documentation for this struct was generated from the following file:
OgreImageResampler.h