OGRE: Ogre::LinearResampler_Float32 Struct Reference
Ogre::LinearResampler_Float32 Struct Reference
Core » Image
#include <OgreImageResampler.h>
Static Public Member Functions
static void scale (const TextureBox &src, PixelFormatGpu srcFormat, const TextureBox &dst, PixelFormatGpu dstFormat)
Member Function Documentation
scale()
static void Ogre::LinearResampler_Float32::scale (const TextureBox & src, PixelFormatGpu srcFormat, const TextureBox & dst, PixelFormatGpu dstFormat) inline static
References ACCUM1, ACCUM2, ACCUM3, ACCUM4, Ogre::TextureBox::atFromOffsettedOrigin(), Ogre::TextureBox::bytesPerImage, Ogre::TextureBox::bytesPerRow, Ogre::TextureBox::depth, Ogre::PixelFormatGpuUtils::getBytesPerPixel(), Ogre::TextureBox::getDepthOrSlices(), Ogre::TextureBox::height, and Ogre::TextureBox::width.
The documentation for this struct was generated from the following file:
OgreImageResampler.h