OGRE-Next: Ogre::EmbeddedZipArchiveFactory Class Reference
Ogre::EmbeddedZipArchiveFactory Class Reference
Core » Resources
Specialisation of ZipArchiveFactory for embedded Zip files.
#include <OgreZip.h>
Public Types
typedef bool(* DecryptEmbeddedZipFileFunc) (size_t pos, void *buf, size_t len)
a function type to decrypt embedded zip file
Public Member Functions
EmbeddedZipArchiveFactory ()
~EmbeddedZipArchiveFactory () override
virtual void convertPath (String &inOutPath) const
Some implementations (i.e.
Archive * createInstance (const String &name) override
Creates a new object.
Archive * createInstance (const String &name, bool readOnly) override
Creates a new object.
void destroyInstance (Archive *ptr) override
Destroys an object which was created by this factory.
const String & getType () const override
Returns the factory type.
Static Public Member Functions
static void addEmbbeddedFile (const String &name, const uint8 *fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc)
Add an embedded file to the embedded file list.
static void removeEmbbeddedFile (const String &name)
Remove an embedded file to the embedded file list.
Detailed Description
Specialisation of ZipArchiveFactory for embedded Zip files.
Member Typedef Documentation
DecryptEmbeddedZipFileFunc
typedef bool(* Ogre::EmbeddedZipArchiveFactory::DecryptEmbeddedZipFileFunc) (size_t pos, void *buf, size_t len)
a function type to decrypt embedded zip file
Parameters
pos pos in file
buf current buffer to decrypt
len - length of buffer
Returns
success
Constructor & Destructor Documentation
EmbeddedZipArchiveFactory()
Ogre::EmbeddedZipArchiveFactory::EmbeddedZipArchiveFactory ()
~EmbeddedZipArchiveFactory()
Ogre::EmbeddedZipArchiveFactory::~EmbeddedZipArchiveFactory () override
Member Function Documentation
addEmbbeddedFile()
static void Ogre::EmbeddedZipArchiveFactory::addEmbbeddedFile (const String & name, const uint8 * fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc) static
Add an embedded file to the embedded file list.
Referenced by Ogre::APKZipArchiveFactory::createInstance().
convertPath()
virtual void Ogre::ArchiveFactory::convertPath (String & inOutPath) const inline virtual inherited
Some implementations (i.e.
APKFileSystemArchive) usually modify the filename. For example in APKFileSystemArchive, "/path/to/localfile.mesh" gets internally stored as "path/to/localfile.mesh" (no leading slash), but across the platform the leading slash is required. The ArchiveManager needs to be aware of this.
Parameters
inOutPath Given the input path, converts it to the final path.
Reimplemented in Ogre::APKFileSystemArchiveFactory, and Ogre::APKZipArchiveFactory.
createInstance() [1/2]
Archive * Ogre::ArchiveFactory::createInstance (const String & name) inline override virtual inherited
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::FactoryObj< Archive >.
References Ogre::ArchiveFactory::createInstance().
Referenced by Ogre::ArchiveFactory::createInstance().
createInstance() [2/2]
Archive * Ogre::EmbeddedZipArchiveFactory::createInstance (const String & name, bool readOnly) inline override virtual
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Reimplemented from Ogre::ZipArchiveFactory.
References OGRE_NEW.
destroyInstance()
void Ogre::ZipArchiveFactory::destroyInstance (Archive * ptr) inline override virtual inherited
Destroys an object which was created by this factory.
Parameters
ptr Pointer to the object to destroy
Implements Ogre::FactoryObj< Archive >.
References OGRE_DELETE.
getType()
const String & Ogre::EmbeddedZipArchiveFactory::getType () const override virtual
Returns the factory type.
Returns
The factory type.
Reimplemented from Ogre::ZipArchiveFactory.
removeEmbbeddedFile()
static void Ogre::EmbeddedZipArchiveFactory::removeEmbbeddedFile (const String & name) static
Remove an embedded file to the embedded file list.
The documentation for this class was generated from the following file:
OgreZip.h