OGRE-Next: Ogre::v1::HardwareBufferManager Class Reference
Ogre::v1::HardwareBufferManager Class Reference
Core » RenderSystem
Singleton wrapper for hardware buffer manager.
#include <OgreHardwareBufferManager.h>
Public Member Functions
HardwareBufferManager (HardwareBufferManagerBase *imp)
~HardwareBufferManager () override
void _forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr &sourceBuffer) override
Internal method that forces the release of copies of a given buffer.
void _forceReleaseBufferCopies (HardwareVertexBuffer *sourceBuffer) override
Internal method that forces the release of copies of a given buffer.
void _freeUnusedBufferCopies () override
Free all unused vertex buffer copies.
void _notifyIndexBufferDestroyed (HardwareIndexBuffer *buf)
Notification that a hardware index buffer has been destroyed.
void _notifyVertexBufferDestroyed (HardwareVertexBuffer *buf)
Notification that a hardware vertex buffer has been destroyed.
void _releaseBufferCopies (bool forceFreeUnused=false) override
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
HardwareVertexBufferSharedPtr allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee *licensee, bool copyData=false) override
Allocates a copy of a given vertex buffer.
HardwareIndexBufferSharedPtr createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer=false) override
Create a hardware index buffer.
HardwareVertexBufferSharedPtr createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer=false) override
Create a hardware vertex buffer.
VertexBufferBinding * createVertexBufferBinding () override
Creates a new VertexBufferBinding.
VertexDeclaration * createVertexDeclaration () override
Creates a new vertex declaration.
void destroyVertexBufferBinding (VertexBufferBinding *binding) override
Destroys a VertexBufferBinding.
void destroyVertexDeclaration (VertexDeclaration *decl) override
Destroys a vertex declaration.
void registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, const HardwareVertexBufferSharedPtr &copy) override
Registers a vertex buffer as a copy of another.
void releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy) override
Manually release a vertex buffer copy for others to subsequently use.
void touchVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy) override
Tell engine that the vertex buffer copy intent to reuse.
Public Member Functions inherited from Ogre::v1::HardwareBufferManagerBase
HardwareBufferManagerBase ()
virtual ~HardwareBufferManagerBase ()
void _notifyIndexBufferDestroyed (HardwareIndexBuffer *buf)
Notification that a hardware index buffer has been destroyed.
void _notifyVertexBufferDestroyed (HardwareVertexBuffer *buf)
Notification that a hardware vertex buffer has been destroyed.
Public Member Functions inherited from Ogre::Singleton< HardwareBufferManager >
Singleton ()
~Singleton ()
Static Public Member Functions
static HardwareBufferManager & getSingleton ()
Override standard Singleton retrieval.
static HardwareBufferManager * getSingletonPtr ()
Override standard Singleton retrieval.
Static Public Member Functions inherited from Ogre::Singleton< HardwareBufferManager >
static HardwareBufferManager & getSingleton ()
static HardwareBufferManager * getSingletonPtr ()
Additional Inherited Members
Public Types inherited from Ogre::v1::HardwareBufferManagerBase
enum BufferLicenseType { BLT_MANUAL_RELEASE , BLT_AUTOMATIC_RELEASE }
Detailed Description
Singleton wrapper for hardware buffer manager.
Constructor & Destructor Documentation
HardwareBufferManager()
Ogre::v1::HardwareBufferManager::HardwareBufferManager (HardwareBufferManagerBase * imp)
~HardwareBufferManager()
Ogre::v1::HardwareBufferManager::~HardwareBufferManager () override
Member Function Documentation
_forceReleaseBufferCopies() [1/2]
void Ogre::v1::HardwareBufferManager::_forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr & sourceBuffer) inline override virtual
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a shared pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::_forceReleaseBufferCopies().
_forceReleaseBufferCopies() [2/2]
void Ogre::v1::HardwareBufferManager::_forceReleaseBufferCopies (HardwareVertexBuffer * sourceBuffer) inline override virtual
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a shared pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::_forceReleaseBufferCopies().
_freeUnusedBufferCopies()
void Ogre::v1::HardwareBufferManager::_freeUnusedBufferCopies () inline override virtual
Free all unused vertex buffer copies.
Remarks
This method free all temporary vertex buffers that not in used. In normally, temporary vertex buffers are subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction. But in some cases you want to free them to save hardware memory (e.g. application was runs in a long time, you might free temporary buffers periodically to avoid memory overload).
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::_freeUnusedBufferCopies().
_notifyIndexBufferDestroyed()
void Ogre::v1::HardwareBufferManager::_notifyIndexBufferDestroyed (HardwareIndexBuffer * buf) inline
Notification that a hardware index buffer has been destroyed.
References Ogre::v1::HardwareBufferManagerBase::_notifyIndexBufferDestroyed().
_notifyVertexBufferDestroyed()
void Ogre::v1::HardwareBufferManager::_notifyVertexBufferDestroyed (HardwareVertexBuffer * buf) inline
Notification that a hardware vertex buffer has been destroyed.
References Ogre::v1::HardwareBufferManagerBase::_notifyVertexBufferDestroyed().
_releaseBufferCopies()
void Ogre::v1::HardwareBufferManager::_releaseBufferCopies (bool forceFreeUnused = false) inline override virtual
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
Parameters
forceFreeUnused If true, free all unused temporary buffers. If false, auto detect and free all unused temporary buffers based on temporary buffers utilization.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::_releaseBufferCopies().
allocateVertexBufferCopy()
HardwareVertexBufferSharedPtr Ogre::v1::HardwareBufferManager::allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee * licensee, bool copyData = false) inline override virtual
Allocates a copy of a given vertex buffer.
Remarks
This method allocates a temporary copy of an existing vertex buffer. This buffer is subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction.
Parameters
sourceBuffer The source buffer to use as a copy.
licenseType The type of license required on this buffer - automatic release causes this class to release licenses every frame so that they can be reallocated anew.
licensee Pointer back to the class requesting the copy, which must implement HardwareBufferLicense in order to be notified when the license expires.
copyData If true, the current data is copied as well as the structure of the buffer/
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::allocateVertexBufferCopy().
createIndexBuffer()
HardwareIndexBufferSharedPtr Ogre::v1::HardwareBufferManager::createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer = false) inline override virtual
Create a hardware index buffer.
Remarks
Note that because buffers can be shared, they are reference counted so you do not need to worry about destroying them this will be done automatically.
Parameters
itype The type in index, either 16- or 32-bit, depending on how many vertices you need to be able to address
numIndexes The number of indexes in the buffer
usage One or more members of the HardwareBuffer::Usage enumeration.
useShadowBuffer If set to true, this buffer will be 'shadowed' by one stored in system memory rather than GPU or AGP memory. You should set this flag if you intend to read data back from the index buffer, because reading data from a buffer in the GPU or AGP memory is very expensive, and is in fact impossible if you specify HBU_WRITE_ONLY for the main buffer. If you use this option, all reads and writes will be done to the shadow buffer, and the shadow buffer will be synchronised with the real buffer at an appropriate time.
Implements Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::createIndexBuffer().
createVertexBuffer()
HardwareVertexBufferSharedPtr Ogre::v1::HardwareBufferManager::createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer = false) inline override virtual
Create a hardware vertex buffer.
Remarks
This method creates a new vertex buffer; this will act as a source of geometry data for rendering objects. Note that because the meaning of the contents of the vertex buffer depends on the usage, this method does not specify a vertex format; the user of this buffer can actually insert whatever data they wish, in any format. However, in order to use this with a RenderOperation, the data in this vertex buffer will have to be associated with a semantic element of the rendering pipeline, e.g. a position, or texture coordinates. This is done using the VertexDeclaration class, which itself contains VertexElement structures referring to the source data.
Note that because vertex buffers can be shared, they are reference counted so you do not need to worry about destroying themm this will be done automatically.
Parameters
vertexSize The size in bytes of each vertex in this buffer; you must calculate this based on the kind of data you expect to populate this buffer with.
numVerts The number of vertices in this buffer.
usage One or more members of the HardwareBuffer::Usage enumeration; you are strongly advised to use HBU_STATIC_WRITE_ONLY wherever possible, if you need to update regularly, consider HBU_DYNAMIC_WRITE_ONLY and useShadowBuffer=true.
useShadowBuffer If set to true, this buffer will be 'shadowed' by one stored in system memory rather than GPU or AGP memory. You should set this flag if you intend to read data back from the vertex buffer, because reading data from a buffer in the GPU or AGP memory is very expensive, and is in fact impossible if you specify HBU_WRITE_ONLY for the main buffer. If you use this option, all reads and writes will be done to the shadow buffer, and the shadow buffer will be synchronised with the real buffer at an appropriate time.
Implements Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::createVertexBuffer().
createVertexBufferBinding()
VertexBufferBinding* Ogre::v1::HardwareBufferManager::createVertexBufferBinding () inline override virtual
Creates a new VertexBufferBinding.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::createVertexBufferBinding().
createVertexDeclaration()
VertexDeclaration* Ogre::v1::HardwareBufferManager::createVertexDeclaration () inline override virtual
Creates a new vertex declaration.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::createVertexDeclaration().
destroyVertexBufferBinding()
void Ogre::v1::HardwareBufferManager::destroyVertexBufferBinding (VertexBufferBinding * binding) inline override virtual
Destroys a VertexBufferBinding.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::destroyVertexBufferBinding().
destroyVertexDeclaration()
void Ogre::v1::HardwareBufferManager::destroyVertexDeclaration (VertexDeclaration * decl) inline override virtual
Destroys a vertex declaration.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::destroyVertexDeclaration().
getSingleton()
static HardwareBufferManager& Ogre::v1::HardwareBufferManager::getSingleton () static
Override standard Singleton retrieval.
Remarks
Why do we do this? Well, it's because the Singleton implementation is in a .h file, which means it gets compiled into anybody who includes it. This is needed for the Singleton template to work, but we actually only want it compiled into the implementation of the class based on the Singleton, not all of them. If we don't change this, we get link errors when trying to use the Singleton-based class from an outside dll.
This method just delegates to the template version anyway, but the implementation stays in this single compilation unit, preventing link errors.
getSingletonPtr()
static HardwareBufferManager* Ogre::v1::HardwareBufferManager::getSingletonPtr () static
Override standard Singleton retrieval.
Remarks
Why do we do this? Well, it's because the Singleton implementation is in a .h file, which means it gets compiled into anybody who includes it. This is needed for the Singleton template to work, but we actually only want it compiled into the implementation of the class based on the Singleton, not all of them. If we don't change this, we get link errors when trying to use the Singleton-based class from an outside dll.
This method just delegates to the template version anyway, but the implementation stays in this single compilation unit, preventing link errors.
registerVertexBufferSourceAndCopy()
void Ogre::v1::HardwareBufferManager::registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, const HardwareVertexBufferSharedPtr & copy) inline override virtual
Registers a vertex buffer as a copy of another.
Remarks
This is useful for registering an existing buffer as a temporary buffer which can be allocated just like a copy.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::registerVertexBufferSourceAndCopy().
releaseVertexBufferCopy()
void Ogre::v1::HardwareBufferManager::releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) inline override virtual
Manually release a vertex buffer copy for others to subsequently use.
Remarks
Only required if the original call to allocateVertexBufferCopy included a licenseType of BLT_MANUAL_RELEASE.
Parameters
bufferCopy The buffer copy. The caller is expected to delete or at least no longer use this reference, since another user may well begin to modify the contents of the buffer.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::releaseVertexBufferCopy().
touchVertexBufferCopy()
void Ogre::v1::HardwareBufferManager::touchVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) inline override virtual
Tell engine that the vertex buffer copy intent to reuse.
Remarks
Ogre internal keep an expired delay counter of BLT_AUTOMATIC_RELEASE buffers, when the counter count down to zero, it'll release for other purposes later. But you can use this function to reset the counter to the internal configured value, keep the buffer not get released for some frames.
Parameters
bufferCopy The buffer copy. The caller is expected to keep this buffer copy for use.
Reimplemented from Ogre::v1::HardwareBufferManagerBase.
References Ogre::v1::HardwareBufferManagerBase::touchVertexBufferCopy().
The documentation for this class was generated from the following file:
OgreHardwareBufferManager.h