OGRE-Next: Ogre::v1::BorderPanelOverlayElement Class Reference
Ogre::v1::BorderPanelOverlayElement Class Reference
Core » Overlays
A specialisation of the PanelOverlayElement to provide a panel with a border.
#include <OgreBorderPanelOverlayElement.h>
Classes
class CmdBorderBottomLeftUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderBottomRightUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderBottomUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderLeftUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderMaterial
Command object for specifying the Material for the border (see ParamCommand).
class CmdBorderRightUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderSize
Command object for specifying border sizes (see ParamCommand).
class CmdBorderTopLeftUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderTopRightUV
Command object for specifying texture coordinates for the border (see ParamCommand).
class CmdBorderTopUV
Command object for specifying texture coordinates for the border (see ParamCommand).
Public Types
typedef MapIterator< ChildContainerMap > ChildContainerIterator
typedef map< String, OverlayContainer * >::type ChildContainerMap
typedef MapIterator< ChildMap > ChildIterator
typedef map< String, OverlayElement * >::type ChildMap
typedef map< size_t, Vector4 >::type CustomParameterMap
Public Member Functions
BorderPanelOverlayElement (const String &name)
Constructor.
~BorderPanelOverlayElement () override
void _addChild (OverlayElement *elem)
virtual void _getClippingRegion (RealRect &clippingRegion)
Gets the clipping region of the element.
virtual Real _getDerivedLeft ()
Gets the 'left' position as derived from own left and that of parents.
virtual Real _getDerivedTop ()
Gets the 'top' position as derived from own left and that of parents.
Real _getHeight () const
Gets the height of this element in relation to the screen (where 1.0 = screen height)
Real _getLeft () const
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
virtual Real _getRelativeHeight ()
Gets the 'height' as derived from own height and metrics mode.
virtual Real _getRelativeWidth ()
Gets the 'width' as derived from own width and metrics mode.
Real _getTop () const
Gets the top of this element in relation to the screen (where 0 = far left, 1.0 = far right)
Real _getWidth () const
Gets the width of this element in relation to the screen (where 1.0 = screen width)
void _notifyParent (OverlayContainer *parent, Overlay *overlay) override
Overridden from OverlayElement.
void _notifyViewport () override
Overridden from OverlayElement.
void _positionsOutOfDate () override
Tell the object and its children to recalculate.
void _releaseManualHardwareResources () override
Notifies that hardware resources were lost.
void _removeChild (const String &name)
void _removeChild (OverlayElement *elem)
void _restoreManualHardwareResources () override
Notifies that hardware resources should be restored.
void _setDimensions (Real width, Real height)
Sets the width and height of this element in relation to the screen (where 1.0 = screen width)
void _setHeight (Real height)
Sets the height of this element in relation to the screen (where 1.0 = screen width)
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
void _setLeft (Real left)
Sets the left of this element in relation to the screen (where 1.0 = screen width)
virtual void _setNullDatablock ()
Sets the datablock to a null pointer.
void _setParent (OverlayContainer *parent)
void _setPosition (Real left, Real top)
Sets the left and top of this element in relation to the screen (where 1.0 = screen width)
void _setTop (Real top)
Sets the top of this element in relation to the screen (where 1.0 = screen width)
void _setWidth (Real width)
Sets the width of this element in relation to the screen (where 1.0 = screen width)
void _update () override
Internal method to update the element based on transforms applied.
virtual void _updateCustomGpuParameter (const GpuProgramParameters_AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
virtual void _updateFromParent ()
Updates this elements transform based on it's parent.
void _updateRenderQueue (RenderQueue *queue, Camera *camera, const Camera *lodCamera) override
Overridden from OverlayElement.
virtual void addChild (OverlayElement *elem)
Adds another OverlayElement to this container.
virtual void addChildImpl (OverlayContainer *cont)
Add a nested container to this container.
virtual void addChildImpl (OverlayElement *elem)
Adds another OverlayElement to this container.
void addPoseWeight (size_t index, float w)
OverlayElement * clone (const String &instanceName) override
virtual bool contains (Real x, Real y) const
Returns true if xy is within the constraints of the component.
void copyFromTemplate (OverlayElement *templateOverlay) override
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
OverlayElement * findElementAt (Real x, Real y) override
This returns a OverlayElement at position x,y.
const String & getBorderMaterialName () const
Gets the name of the material to use for the borders.
Real getBottomBorderSize () const
Gets the size of the bottom border.
String getBottomBorderUVString () const
String getBottomLeftBorderUVString () const
String getBottomRightBorderUVString () const
virtual const DisplayString & getCaption () const
Gets the caption for this element.
virtual bool getCastsShadows () const
Method which reports whether this renderable would normally cast a shadow.
virtual OverlayElement * getChild (const String &name)
Gets the named child of this container.
virtual ChildContainerIterator getChildContainerIterator ()
Gets an iterator for just the container children of this object.
virtual ChildIterator getChildIterator ()
Gets an object for iterating over all the children of this object.
virtual const ColourValue & getColour () const
Gets the colour for this element.
uint8 getCurrentMaterialLod () const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
const CustomParameterMap & getCustomParameters () const
HlmsDatablock * getDatablock () const
const String & getDatablockOrMaterialName () const
Real getHeight () const
Gets the height of this element in relation to the screen (where 1.0 = screen height)
uint32 getHlmsCasterHash () const
uint32 getHlmsHash () const
virtual GuiHorizontalAlignment getHorizontalAlignment () const
Gets the horizontal alignment for this element.
Real getLeft () const
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
Real getLeftBorderSize () const
Gets the size of the left border.
String getLeftBorderUVString () const
const LightList & getLights () const override
Gets a list of lights, ordered relative to how close they are to this renderable.
const MaterialPtr & getMaterial () const
See Renderable.
virtual const String & getMaterialName () const
Gets the name of the material this element uses.
virtual GuiMetricsMode getMetricsMode () const
Retrieves the current settings of how the element metrics are interpreted.
const String & getName () const
Gets the name of this overlay.
unsigned short getNumPoses () const
virtual unsigned short getNumWorldTransforms () const
Returns the number of world transform matrices this renderable requires.
ParamDictionary * getParamDictionary ()
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary () const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters () const
Retrieves a list of parameters valid for this object.
OverlayContainer * getParent ()
Returns the parent container.
virtual bool getPolygonModeOverrideable () const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
bool getPoseHalfPrecision () const
bool getPoseNormals () const
TexBufferPacked * getPoseTexBuffer () const
float getPoseWeight (size_t index) const
float * getPoseWeights () const
void getRenderOperation (v1::RenderOperation &op, bool casterPass) override
See Renderable.
uint8 getRenderQueueSubGroup () const
Real getRightBorderSize () const
Gets the size of the right border.
String getRightBorderUVString () const
const OverlayElement * getSourceTemplate () const
Returns the SourceTemplate for this element.
Real getTileX (ushort layer=0) const
Real getTileY (ushort layer=0) const
Gets the number of times the texture should repeat vertically.
Real getTop () const
Gets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
Real getTopBorderSize () const
Gets the size of the top border.
String getTopBorderUVString () const
String getTopLeftBorderUVString () const
String getTopRightBorderUVString () const
const String & getTypeName () const override
Gets the type name of the element.
bool getUseIdentityProjection () const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView () const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic () const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix () const
Returns whether the world matrix is an identity matrix.
virtual OGRE_DEPRECATED const Any & getUserAny () const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
void getUV (Real &u1, Real &v1, Real &u2, Real &v2) const
Get the uv coordinates for the panel.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
virtual GuiVerticalAlignment getVerticalAlignment () const
Gets the vertical alignment for this element.
Real getWidth () const
Gets the width of this element in relation to the screen (where 1.0 = screen width)
void getWorldTransforms (Matrix4 *xform) const override
See Renderable.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation () const
virtual void hide ()
Hides this element if it was visible.
void initialise () override
Initialise gui element.
virtual bool isChildrenProcessEvents () const
Should this container pass events to their children.
virtual bool isCloneable () const
bool isContainer () const override
Overridden from OverlayElement.
bool isEnabled () const
virtual bool isKeyEnabled () const
bool isTransparent () const
Returns whether this panel is transparent.
bool isVisible () const
Returns whether or not the element is visible.
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
virtual void removeChild (const String &name)
Removes a named element from this container.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void setBorderMaterialName (const String &name)
Sets the name of the material to use for the borders.
void setBorderSize (Real left, Real right, Real top, Real bottom)
Sets the size of the border separately for all borders.
void setBorderSize (Real sides, Real topAndBottom)
Sets the size of the border, with different sizes for vertical and horizontal borders.
void setBorderSize (Real size)
Sets the size of the border.
void setBottomBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom edge of the border.
void setBottomLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom-left corner of the border.
void setBottomRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom-right corner of the border.
virtual void setCaption (const DisplayString &text)
Sets the caption on elements that support it.
virtual void setChildrenProcessEvents (bool val)
Should this container pass events to their children.
virtual void setCloneable (bool c)
virtual void setColour (const ColourValue &col)
Sets the colour on elements that support it.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
void setDimensions (Real width, Real height)
Sets the dimensions of this element in relation to the screen (1.0 = screen width/height).
virtual void setEnabled (bool b)
void setHeight (Real height)
Sets the height of this element in relation to the screen (where 1.0 = screen height)
virtual void setHorizontalAlignment (GuiHorizontalAlignment gha)
Sets the horizontal origin for this element.
void setLeft (Real left)
Sets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
void setLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the left edge of the border.
virtual void setMaterial (const MaterialPtr &material)
Sets the given material. Overrides HLMS materials.
void setMaterialName (const String &matName) override
Overridden from OverlayElement.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS.
void setMetricsMode (GuiMetricsMode gmm) override
Tells this element how to interpret the position and dimension values it is given.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setPoseWeight (size_t index, float w)
void setPosition (Real left, Real top)
Sets the position of the top-left corner of the element, relative to the screen size (1.0 = screen width / height)
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
void setRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the right edge of the border.
void setTiling (Real x, Real y, ushort layer=0)
Sets the number of times textures should repeat.
void setTop (Real Top)
Sets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
void setTopBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top edge of the border.
void setTopLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top-left corner of the border.
void setTopRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top-right corner of the border.
void setTransparent (bool isTransparent)
Sets whether this panel is transparent (used only as a grouping level), or if it is actually rendered.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
void setUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the panel.
virtual void setVerticalAlignment (GuiVerticalAlignment gva)
Sets the vertical origin for this element.
void setWidth (Real width)
Sets the width of this element in relation to the screen (where 1.0 = screen width)
virtual void show ()
Shows this element if it was hidden.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
static uint8 getDefaultRenderQueueSubGroup ()
static void setDefaultRenderQueueSubGroup (uint8 subGroup)
Sets the default render queue sub group for all future Renderable instances.
Public Attributes
uint8 mCustomParameter
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
bool mRenderableVisible
Control visibility at Renderable (e.g.
Friends
class BorderRenderable
Detailed Description
A specialisation of the PanelOverlayElement to provide a panel with a border.
Remarks
Whilst the standard panel can use a single tiled material, this class allows panels with a tileable backdrop plus a border texture. This is handy for large panels that are too big to use a single large texture with a border, or for multiple different size panels where you want the border a constant width but the center to repeat.
In addition to the usual PanelOverlayElement properties, this class has a 'border material', which specifies the material used for the edges of the panel, a border width (which can either be constant all the way around, or specified per edge), and the texture coordinates for each of the border sections.
Member Typedef Documentation
ChildContainerIterator
typedef MapIterator<ChildContainerMap> Ogre::v1::OverlayContainer::ChildContainerIterator inherited
ChildContainerMap
typedef map<String,OverlayContainer*>::type Ogre::v1::OverlayContainer::ChildContainerMap inherited
ChildIterator
typedef MapIterator<ChildMap> Ogre::v1::OverlayContainer::ChildIterator inherited
ChildMap
typedef map<String,OverlayElement*>::type Ogre::v1::OverlayContainer::ChildMap inherited
CustomParameterMap
typedef map<size_t,Vector4>::type Ogre::Renderable::CustomParameterMap inherited
Constructor & Destructor Documentation
BorderPanelOverlayElement()
Ogre::v1::BorderPanelOverlayElement::BorderPanelOverlayElement (const String & name)
Constructor.
~BorderPanelOverlayElement()
Ogre::v1::BorderPanelOverlayElement::~BorderPanelOverlayElement () override
Member Function Documentation
_addChild()
void Ogre::v1::OverlayContainer::_addChild (OverlayElement * elem) inherited
_getClippingRegion()
virtual void Ogre::v1::OverlayElement::_getClippingRegion (RealRect & clippingRegion) virtual inherited
Gets the clipping region of the element.
_getDerivedLeft()
virtual Real Ogre::v1::OverlayElement::_getDerivedLeft () virtual inherited
Gets the 'left' position as derived from own left and that of parents.
_getDerivedTop()
virtual Real Ogre::v1::OverlayElement::_getDerivedTop () virtual inherited
Gets the 'top' position as derived from own left and that of parents.
_getHeight()
Real Ogre::v1::OverlayElement::_getHeight () const inline inherited
Gets the height of this element in relation to the screen (where 1.0 = screen height)
_getLeft()
Real Ogre::v1::OverlayElement::_getLeft () const inline inherited
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
_getRelativeHeight()
virtual Real Ogre::v1::OverlayElement::_getRelativeHeight () virtual inherited
Gets the 'height' as derived from own height and metrics mode.
_getRelativeWidth()
virtual Real Ogre::v1::OverlayElement::_getRelativeWidth () virtual inherited
Gets the 'width' as derived from own width and metrics mode.
_getTop()
Real Ogre::v1::OverlayElement::_getTop () const inline inherited
Gets the top of this element in relation to the screen (where 0 = far left, 1.0 = far right)
_getWidth()
Real Ogre::v1::OverlayElement::_getWidth () const inline inherited
Gets the width of this element in relation to the screen (where 1.0 = screen width)
_notifyParent()
void Ogre::v1::OverlayContainer::_notifyParent (OverlayContainer * parent, Overlay * overlay) override virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
_notifyViewport()
void Ogre::v1::OverlayContainer::_notifyViewport () override virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
_positionsOutOfDate()
void Ogre::v1::OverlayContainer::_positionsOutOfDate () override virtual inherited
Tell the object and its children to recalculate.
Reimplemented from Ogre::v1::OverlayElement.
_releaseManualHardwareResources()
void Ogre::v1::BorderPanelOverlayElement::_releaseManualHardwareResources () override virtual
Notifies that hardware resources were lost.
Reimplemented from Ogre::v1::OverlayElement.
_removeChild() [1/2]
void Ogre::v1::OverlayContainer::_removeChild (const String & name) inherited
_removeChild() [2/2]
void Ogre::v1::OverlayContainer::_removeChild (OverlayElement * elem) inline inherited
References Ogre::v1::OverlayContainer::_removeChild(), and Ogre::v1::OverlayElement::getName().
Referenced by Ogre::v1::OverlayContainer::_removeChild().
_restoreManualHardwareResources()
void Ogre::v1::BorderPanelOverlayElement::_restoreManualHardwareResources () override virtual
Notifies that hardware resources should be restored.
Reimplemented from Ogre::v1::OverlayElement.
_setDimensions()
void Ogre::v1::OverlayElement::_setDimensions (Real width, Real height) inherited
Sets the width and height of this element in relation to the screen (where 1.0 = screen width)
_setHeight()
void Ogre::v1::OverlayElement::_setHeight (Real height) inherited
Sets the height of this element in relation to the screen (where 1.0 = screen width)
_setHlmsHashes()
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual inherited
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
_setLeft()
void Ogre::v1::OverlayElement::_setLeft (Real left) inherited
Sets the left of this element in relation to the screen (where 1.0 = screen width)
_setNullDatablock()
virtual void Ogre::Renderable::_setNullDatablock () virtual inherited
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
_setParent()
void Ogre::v1::OverlayElement::_setParent (OverlayContainer * parent) inline inherited
_setPosition()
void Ogre::v1::OverlayElement::_setPosition (Real left, Real top) inherited
Sets the left and top of this element in relation to the screen (where 1.0 = screen width)
_setTop()
void Ogre::v1::OverlayElement::_setTop (Real top) inherited
Sets the top of this element in relation to the screen (where 1.0 = screen width)
_setWidth()
void Ogre::v1::OverlayElement::_setWidth (Real width) inherited
Sets the width of this element in relation to the screen (where 1.0 = screen width)
_update()
void Ogre::v1::BorderPanelOverlayElement::_update () override virtual
Internal method to update the element based on transforms applied.
Reimplemented from Ogre::v1::OverlayElement.
_updateCustomGpuParameter()
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters_AutoConstantEntry & constantEntry, GpuProgramParameters * params) const virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::v1::SubEntity.
_updateFromParent()
virtual void Ogre::v1::OverlayElement::_updateFromParent () virtual inherited
Updates this elements transform based on it's parent.
_updateRenderQueue()
void Ogre::v1::BorderPanelOverlayElement::_updateRenderQueue (RenderQueue * queue, Camera * camera, const Camera * lodCamera) override virtual
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
addChild()
virtual void Ogre::v1::OverlayContainer::addChild (OverlayElement * elem) virtual inherited
Adds another OverlayElement to this container.
addChildImpl() [1/2]
virtual void Ogre::v1::OverlayContainer::addChildImpl (OverlayContainer * cont) virtual inherited
Add a nested container to this container.
addChildImpl() [2/2]
virtual void Ogre::v1::OverlayContainer::addChildImpl (OverlayElement * elem) virtual inherited
Adds another OverlayElement to this container.
addPoseWeight()
void Ogre::Renderable::addPoseWeight (size_t index, float w) inherited
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
clone()
OverlayElement * Ogre::v1::OverlayContainer::clone (const String & instanceName) override virtual inherited
Reimplemented from Ogre::v1::OverlayElement.
contains()
virtual bool Ogre::v1::OverlayElement::contains (Real x, Real y) const virtual inherited
Returns true if xy is within the constraints of the component.
copyFromTemplate()
void Ogre::v1::OverlayContainer::copyFromTemplate (OverlayElement * templateOverlay) override virtual inherited
Reimplemented from Ogre::v1::OverlayElement.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
findElementAt()
OverlayElement * Ogre::v1::OverlayContainer::findElementAt (Real x, Real y) override virtual inherited
This returns a OverlayElement at position x,y.
Reimplemented from Ogre::v1::OverlayElement.
getBorderMaterialName()
const String & Ogre::v1::BorderPanelOverlayElement::getBorderMaterialName () const
Gets the name of the material to use for the borders.
getBottomBorderSize()
Real Ogre::v1::BorderPanelOverlayElement::getBottomBorderSize () const
Gets the size of the bottom border.
getBottomBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getBottomBorderUVString () const
getBottomLeftBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getBottomLeftBorderUVString () const
getBottomRightBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getBottomRightBorderUVString () const
getCaption()
virtual const DisplayString & Ogre::v1::OverlayElement::getCaption () const virtual inherited
Gets the caption for this element.
getCastsShadows()
virtual bool Ogre::Renderable::getCastsShadows () const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::IfdProbeVisualizer, Ogre::VoxelVisualizer, Ogre::ManualObject::ManualObjectSection, Ogre::Rectangle2D, Ogre::v1::SubEntity, Ogre::SubItem, and Ogre::WireAabb.
getChild()
virtual OverlayElement * Ogre::v1::OverlayContainer::getChild (const String & name) virtual inherited
Gets the named child of this container.
getChildContainerIterator()
virtual ChildContainerIterator Ogre::v1::OverlayContainer::getChildContainerIterator () virtual inherited
Gets an iterator for just the container children of this object.
Remarks
Good for cascading updates without having to use RTTI
getChildIterator()
virtual ChildIterator Ogre::v1::OverlayContainer::getChildIterator () virtual inherited
Gets an object for iterating over all the children of this object.
getColour()
virtual const ColourValue & Ogre::v1::OverlayElement::getColour () const virtual inherited
Gets the colour for this element.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
getCurrentMaterialLod()
uint8 Ogre::Renderable::getCurrentMaterialLod () const inline inherited
getCustomParameter()
const Vector4 & Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References OGRE_EXCEPT.
getCustomParameters()
const CustomParameterMap & Ogre::Renderable::getCustomParameters () const inline inherited
getDatablock()
HlmsDatablock * Ogre::Renderable::getDatablock () const inline inherited
getDatablockOrMaterialName()
const String & Ogre::Renderable::getDatablockOrMaterialName () const inherited
getDefaultRenderQueueSubGroup()
static uint8 Ogre::Renderable::getDefaultRenderQueueSubGroup () inline static inherited
getHeight()
Real Ogre::v1::OverlayElement::getHeight () const inherited
Gets the height of this element in relation to the screen (where 1.0 = screen height)
getHlmsCasterHash()
uint32 Ogre::Renderable::getHlmsCasterHash () const inline inherited
getHlmsHash()
uint32 Ogre::Renderable::getHlmsHash () const inline inherited
getHorizontalAlignment()
virtual GuiHorizontalAlignment Ogre::v1::OverlayElement::getHorizontalAlignment () const virtual inherited
Gets the horizontal alignment for this element.
getLeft()
Real Ogre::v1::OverlayElement::getLeft () const inherited
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
getLeftBorderSize()
Real Ogre::v1::BorderPanelOverlayElement::getLeftBorderSize () const
Gets the size of the left border.
getLeftBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getLeftBorderUVString () const
getLights()
const LightList & Ogre::v1::OverlayElement::getLights () const inline override virtual inherited
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
getMaterial()
const MaterialPtr & Ogre::v1::OverlayElement::getMaterial () const inherited
See Renderable.
getMaterialName()
virtual const String & Ogre::v1::OverlayElement::getMaterialName () const virtual inherited
Gets the name of the material this element uses.
getMetricsMode()
virtual GuiMetricsMode Ogre::v1::OverlayElement::getMetricsMode () const virtual inherited
Retrieves the current settings of how the element metrics are interpreted.
getName()
const String & Ogre::v1::OverlayElement::getName () const inherited
Gets the name of this overlay.
Referenced by Ogre::v1::OverlayContainer::_removeChild().
getNumPoses()
unsigned short Ogre::Renderable::getNumPoses () const inherited
getNumWorldTransforms()
virtual unsigned short Ogre::Renderable::getNumWorldTransforms () const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::v1::BorderRenderable, and Ogre::v1::SubEntity.
getParamDictionary() [1/2]
ParamDictionary * Ogre::StringInterface::getParamDictionary () inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary * Ogre::StringInterface::getParamDictionary () const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList & Ogre::StringInterface::getParameters () const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getParent()
OverlayContainer * Ogre::v1::OverlayElement::getParent () inherited
Returns the parent container.
getPolygonModeOverrideable()
virtual bool Ogre::Renderable::getPolygonModeOverrideable () const inline virtual inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
getPoseHalfPrecision()
bool Ogre::Renderable::getPoseHalfPrecision () const inherited
getPoseNormals()
bool Ogre::Renderable::getPoseNormals () const inherited
getPoseTexBuffer()
TexBufferPacked * Ogre::Renderable::getPoseTexBuffer () const inherited
getPoseWeight()
float Ogre::Renderable::getPoseWeight (size_t index) const inherited
getPoseWeights()
float * Ogre::Renderable::getPoseWeights () const inherited
getRenderOperation()
void Ogre::v1::PanelOverlayElement::getRenderOperation (v1::RenderOperation & op, bool casterPass) override virtual inherited
See Renderable.
Implements Ogre::Renderable.
getRenderQueueSubGroup()
uint8 Ogre::Renderable::getRenderQueueSubGroup () const inline inherited
getRightBorderSize()
Real Ogre::v1::BorderPanelOverlayElement::getRightBorderSize () const
Gets the size of the right border.
getRightBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getRightBorderUVString () const
getSourceTemplate()
const OverlayElement * Ogre::v1::OverlayElement::getSourceTemplate () const inline inherited
Returns the SourceTemplate for this element.
getTileX()
Real Ogre::v1::PanelOverlayElement::getTileX (ushort layer = 0) const inherited
getTileY()
Real Ogre::v1::PanelOverlayElement::getTileY (ushort layer = 0) const inherited
Gets the number of times the texture should repeat vertically.
Parameters
layer The texture layer to specify (only needs to be altered if you're using a multi-texture layer material)
getTop()
Real Ogre::v1::OverlayElement::getTop () const inherited
Gets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
getTopBorderSize()
Real Ogre::v1::BorderPanelOverlayElement::getTopBorderSize () const
Gets the size of the top border.
getTopBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getTopBorderUVString () const
getTopLeftBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getTopLeftBorderUVString () const
getTopRightBorderUVString()
String Ogre::v1::BorderPanelOverlayElement::getTopRightBorderUVString () const
getTypeName()
const String & Ogre::v1::BorderPanelOverlayElement::getTypeName () const override virtual
Gets the type name of the element.
All concrete subclasses must implement this.
Implements Ogre::v1::OverlayElement.
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection () const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView () const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
getUseIdentityViewProjMatrixIsDynamic()
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic () const inline virtual inherited
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
getUseIdentityWorldMatrix()
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix () const inline virtual inherited
Returns whether the world matrix is an identity matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
getUserAny()
virtual OGRE_DEPRECATED const Any & Ogre::Renderable::getUserAny () const inline virtual inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead. Retrieves the custom user value associated with this object.
getUserObjectBindings() [1/2]
UserObjectBindings & Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/2]
const UserObjectBindings & Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUV()
void Ogre::v1::PanelOverlayElement::getUV (Real & u1, Real & v1, Real & u2, Real & v2) const inherited
Get the uv coordinates for the panel.
getVaos()
const VertexArrayObjectArray & Ogre::Renderable::getVaos (VertexPass vertexPass) const inline inherited
getVerticalAlignment()
virtual GuiVerticalAlignment Ogre::v1::OverlayElement::getVerticalAlignment () const virtual inherited
Gets the vertical alignment for this element.
getWidth()
Real Ogre::v1::OverlayElement::getWidth () const inherited
Gets the width of this element in relation to the screen (where 1.0 = screen width)
getWorldTransforms()
void Ogre::v1::OverlayElement::getWorldTransforms (Matrix4 * xform) const override virtual inherited
See Renderable.
Implements Ogre::Renderable.
Referenced by Ogre::v1::BorderRenderable::getWorldTransforms().
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
hasSkeletonAnimation()
bool Ogre::Renderable::hasSkeletonAnimation () const inline inherited
hide()
virtual void Ogre::v1::OverlayElement::hide () virtual inherited
Hides this element if it was visible.
initialise()
void Ogre::v1::BorderPanelOverlayElement::initialise () override virtual
Initialise gui element.
Implements Ogre::v1::OverlayElement.
isChildrenProcessEvents()
virtual bool Ogre::v1::OverlayContainer::isChildrenProcessEvents () const inline virtual inherited
Should this container pass events to their children.
isCloneable()
virtual bool Ogre::v1::OverlayElement::isCloneable () const inline virtual inherited
isContainer()
bool Ogre::v1::OverlayContainer::isContainer () const inline override virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
isEnabled()
bool Ogre::v1::OverlayElement::isEnabled () const inherited
isKeyEnabled()
virtual bool Ogre::v1::OverlayElement::isKeyEnabled () const inline virtual inherited
isTransparent()
bool Ogre::v1::PanelOverlayElement::isTransparent () const inherited
Returns whether this panel is transparent.
isVisible()
bool Ogre::v1::OverlayElement::isVisible () const inherited
Returns whether or not the element is visible.
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
preRender()
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::v1::BillboardChain.
removeChild()
virtual void Ogre::v1::OverlayContainer::removeChild (const String & name) virtual inherited
Removes a named element from this container.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
setBorderMaterialName()
void Ogre::v1::BorderPanelOverlayElement::setBorderMaterialName (const String & name)
Sets the name of the material to use for the borders.
setBorderSize() [1/3]
void Ogre::v1::BorderPanelOverlayElement::setBorderSize (Real left, Real right, Real top, Real bottom)
Sets the size of the border separately for all borders.
Remarks
This method sets a size all borders separately. Remember that the dimensions specified here are in relation to the size of the screen, so 0.1 is 1/10th of the screen width or height. Also note that because most screen resolutions are 1.333:1 width:height ratio that using the same border size will look slightly bigger across than up.
Parameters
left The size of the left border as a factor of the screen dimensions ie 0.2 is one-fifth of the screen size.
right The size of the left border as a factor of the screen dimensions.
top The size of the top border as a factor of the screen dimensions.
bottom The size of the bottom border as a factor of the screen dimensions.
setBorderSize() [2/3]
void Ogre::v1::BorderPanelOverlayElement::setBorderSize (Real sides, Real topAndBottom)
Sets the size of the border, with different sizes for vertical and horizontal borders.
Remarks
This method sets a size for the side and top / bottom borders separately. Remember that the dimensions specified here are in relation to the size of the screen, so 0.1 is 1/10th of the screen width or height. Also note that because most screen resolutions are 1.333:1 width:height ratio that using the same border size will look slightly bigger across than up.
Parameters
sides The size of the side borders as a factor of the screen dimensions ie 0.2 is one-fifth of the screen size.
topAndBottom The size of the top and bottom borders as a factor of the screen dimensions.
setBorderSize() [3/3]
void Ogre::v1::BorderPanelOverlayElement::setBorderSize (Real size)
Sets the size of the border.
Remarks
This method sets a constant size for all borders. There are also alternative methods which allow you to set border widths for individual edges separately. Remember that the dimensions specified here are in relation to the size of the screen, so 0.1 is 1/10th of the screen width or height. Also note that because most screen resolutions are 1.333:1 width:height ratio that using the same border size will look slightly bigger across than up.
Parameters
size The size of the border as a factor of the screen dimensions ie 0.2 is one-fifth of the screen size.
setBottomBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setBottomBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom edge of the border.
Remarks
See setLeftBorderUV.
setBottomLeftBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setBottomLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom-left corner of the border.
Remarks
See setLeftBorderUV.
setBottomRightBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setBottomRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the bottom-right corner of the border.
Remarks
See setLeftBorderUV.
setCaption()
virtual void Ogre::v1::OverlayElement::setCaption (const DisplayString & text) virtual inherited
Sets the caption on elements that support it.
Remarks
This property doesn't do something on all elements, just those that support it. However, being a common requirement it is in the top-level interface to avoid having to set it via the StringInterface all the time.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
setChildrenProcessEvents()
virtual void Ogre::v1::OverlayContainer::setChildrenProcessEvents (bool val) inline virtual inherited
Should this container pass events to their children.
setCloneable()
virtual void Ogre::v1::OverlayElement::setCloneable (bool c) inline virtual inherited
setColour()
virtual void Ogre::v1::OverlayElement::setColour (const ColourValue & col) virtual inherited
Sets the colour on elements that support it.
Remarks
This property doesn't do something on all elements, just those that support it. However, being a common requirement it is in the top-level interface to avoid having to set it via the StringInterface all the time.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
setDatablock() [1/2]
virtual void Ogre::Renderable::setDatablock (HlmsDatablock * datablock) virtual inherited
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented in Ogre::v1::SubEntity, Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
setDatablock() [2/2]
void Ogre::Renderable::setDatablock (IdString datablockName) inherited
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
setDatablockOrMaterialName()
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName) inherited
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
setDefaultRenderQueueSubGroup()
static void Ogre::Renderable::setDefaultRenderQueueSubGroup (uint8 subGroup) inline static inherited
Sets the default render queue sub group for all future Renderable instances.
setDimensions()
void Ogre::v1::OverlayElement::setDimensions (Real width, Real height) inherited
Sets the dimensions of this element in relation to the screen (1.0 = screen width/height).
setEnabled()
virtual void Ogre::v1::OverlayElement::setEnabled (bool b) virtual inherited
setHeight()
void Ogre::v1::OverlayElement::setHeight (Real height) inherited
Sets the height of this element in relation to the screen (where 1.0 = screen height)
setHorizontalAlignment()
virtual void Ogre::v1::OverlayElement::setHorizontalAlignment (GuiHorizontalAlignment gha) virtual inherited
Sets the horizontal origin for this element.
Remarks
By default, the horizontal origin for a OverlayElement is the left edge of the parent container (or the screen if this is a root element). You can alter this by calling this method, which is especially useful when you want to use pixel-based metrics (see setMetricsMode) since in this mode you can't use relative positioning.
For example, if you were using GMM_PIXELS metrics mode, and you wanted to place a 30x30 pixel crosshair in the center of the screen, you would use GHA_CENTER with a 'left' property of -15.
Note that neither GHA_CENTER or GHA_RIGHT alter the position of the element based on it's width, you have to alter the 'left' to a negative number to do that; all this does is establish the origin. This is because this way you can align multiple things in the center and right with different 'left' offsets for maximum flexibility.
setLeft()
void Ogre::v1::OverlayElement::setLeft (Real left) inherited
Sets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
setLeftBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the left edge of the border.
Remarks
The border panel uses 8 panels for the border (9 including the center). Imagine a table with 3 rows and 3 columns. The corners are always the same size, but the edges stretch depending on how big the panel is. Those who have done resizable HTML tables will be familiar with this approach.
We only require 2 sets of uv coordinates, one for the top-left and one for the bottom-right of the panel, since it is assumed the sections are aligned on the texture.
setMaterial()
virtual void Ogre::Renderable::setMaterial (const MaterialPtr & material) virtual inherited
Sets the given material. Overrides HLMS materials.
Reimplemented in Ogre::v1::SimpleRenderable, Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
setMaterialName() [1/2]
void Ogre::v1::PanelOverlayElement::setMaterialName (const String & matName) override virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
setMaterialName() [2/2]
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName) inherited
Sets the name of the Material to be used. Prefer using HLMS.
See also
setHlms
setMetricsMode()
void Ogre::v1::BorderPanelOverlayElement::setMetricsMode (GuiMetricsMode gmm) override virtual
Tells this element how to interpret the position and dimension values it is given.
Remarks
By default, OverlayElements are positioned and sized according to relative dimensions of the screen. This is to ensure portability between different resolutions when you want things to be positioned and sized the same way across all resolutions. However, sometimes you want things to be sized according to fixed pixels. In order to do this, you can call this method with the parameter GMM_PIXELS. Note that if you then want to place your element relative to the center, right or bottom of it's parent, you will need to use the setHorizontalAlignment and setVerticalAlignment methods.
Reimplemented from Ogre::v1::OverlayElement.
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setPolygonModeOverrideable()
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
setPoseWeight()
void Ogre::Renderable::setPoseWeight (size_t index, float w) inherited
setPosition()
void Ogre::v1::OverlayElement::setPosition (Real left, Real top) inherited
Sets the position of the top-left corner of the element, relative to the screen size (1.0 = screen width / height)
setRenderQueueSubGroup()
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline inherited
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits)
See also
RenderQueue
setRightBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the right edge of the border.
Remarks
See setLeftBorderUV.
setTiling()
void Ogre::v1::PanelOverlayElement::setTiling (Real x, Real y, ushort layer = 0) inherited
Sets the number of times textures should repeat.
Parameters
x The number of times the texture should repeat horizontally
y The number of times the texture should repeat vertically
layer The texture layer to specify (only needs to be altered if you're using a multi-texture layer material)
setTop()
void Ogre::v1::OverlayElement::setTop (Real Top) inherited
Sets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
setTopBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setTopBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top edge of the border.
Remarks
See setLeftBorderUV.
setTopLeftBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setTopLeftBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top-left corner of the border.
Remarks
See setLeftBorderUV.
setTopRightBorderUV()
void Ogre::v1::BorderPanelOverlayElement::setTopRightBorderUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the top-right corner of the border.
Remarks
See setLeftBorderUV.
setTransparent()
void Ogre::v1::PanelOverlayElement::setTransparent (bool isTransparent) inherited
Sets whether this panel is transparent (used only as a grouping level), or if it is actually rendered.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
setUserAny()
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead. Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
setUV()
void Ogre::v1::PanelOverlayElement::setUV (Real u1, Real v1, Real u2, Real v2) inherited
Sets the texture coordinates for the panel.
setVerticalAlignment()
virtual void Ogre::v1::OverlayElement::setVerticalAlignment (GuiVerticalAlignment gva) virtual inherited
Sets the vertical origin for this element.
Remarks
By default, the vertical origin for a OverlayElement is the top edge of the parent container (or the screen if this is a root element). You can alter this by calling this method, which is especially useful when you want to use pixel-based metrics (see setMetricsMode) since in this mode you can't use relative positioning.
For example, if you were using GMM_PIXELS metrics mode, and you wanted to place a 30x30 pixel crosshair in the center of the screen, you would use GHA_CENTER with a 'top' property of -15.
Note that neither GVA_CENTER or GVA_BOTTOM alter the position of the element based on it's height, you have to alter the 'top' to a negative number to do that; all this does is establish the origin. This is because this way you can align multiple things in the center and bottom with different 'top' offsets for maximum flexibility.
setWidth()
void Ogre::v1::OverlayElement::setWidth (Real width) inherited
Sets the width of this element in relation to the screen (where 1.0 = screen width)
show()
virtual void Ogre::v1::OverlayElement::show () virtual inherited
Shows this element if it was hidden.
Friends And Related Function Documentation
BorderRenderable
friend class BorderRenderable friend
Member Data Documentation
mCustomParameter
uint8 Ogre::Renderable::mCustomParameter inherited
mHlmsGlobalIndex
uint32 Ogre::Renderable::mHlmsGlobalIndex inherited
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
mRenderableVisible
bool Ogre::Renderable::mRenderableVisible inherited
Control visibility at Renderable (e.g.
SubMesh) level
Note that if our MovableObject owner called MovableObject::setVisible(false) we won't get rendered. Both must be true in order to render.
Remarks
PUBLIC VARIABLE. This variable can be altered directly. Changes are reflected immediately.
The documentation for this class was generated from the following file:
OgreBorderPanelOverlayElement.h