OGRE-Next: Ogre::v1::DefaultHardwareIndexBuffer Class Reference
Ogre::v1::DefaultHardwareIndexBuffer Class Reference
Core » RenderSystem
Specialisation of HardwareIndexBuffer for emulation.
#include <OgreDefaultHardwareBufferManager.h>
Public Types
typedef Ogre::IndexType IndexType
enum LockOptions {
HBL_NORMAL , HBL_DISCARD , HBL_READ_ONLY , HBL_NO_OVERWRITE ,
HBL_WRITE_ONLY
}
Locking options.
enum Usage {
HBU_STATIC = 1 , HBU_DYNAMIC = 2 , HBU_WRITE_ONLY = 4 , HBU_DISCARDABLE = 8 ,
HBU_STATIC_WRITE_ONLY = 5 , HBU_DYNAMIC_WRITE_ONLY = 6 , HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
DefaultHardwareIndexBuffer (IndexType idxType, size_t numIndexes, HardwareBuffer::Usage usage)
~DefaultHardwareIndexBuffer () override
virtual void _updateFromShadow ()
Updates the real buffer from the shadow buffer, if required.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
size_t getIndexSize () const
Get the size in bytes of each index.
HardwareBufferManagerBase * getManager () const
Return the manager of this buffer, if any.
size_t getNumIndexes () const
Get the number of indexes in this buffer.
virtual void * getRenderSystemData ()
An internal function that should be used only by a render system for internal use.
size_t getSizeInBytes () const
Returns the size of this buffer in bytes.
IndexType getType () const
Get the type of indexes used in this buffer.
Usage getUsage () const
Returns the Usage flags with which this buffer was created.
bool hasShadowBuffer () const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked () const
Returns whether or not this buffer is currently locked.
bool isSystemMemory () const
Returns whether this buffer is held in system memory.
void * lock (LockOptions options)
Lock the entire buffer for (potentially) reading / writing.
void * lock (size_t offset, size_t length, LockOptions options) override
Override HardwareBuffer to turn off all shadowing.
void readData (size_t offset, size_t length, void *pDest) override
See HardwareBuffer.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
void unlock () override
Override HardwareBuffer to turn off all shadowing.
void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false) override
See HardwareBuffer.
Static Public Attributes
static const IndexType IT_16BIT = Ogre::IT_16BIT
static const IndexType IT_32BIT = Ogre::IT_32BIT
Detailed Description
Specialisation of HardwareIndexBuffer for emulation.
Member Typedef Documentation
IndexType
typedef Ogre::IndexType Ogre::v1::HardwareIndexBuffer::IndexType inherited
Member Enumeration Documentation
LockOptions
enum Ogre::v1::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
Usage
enum Ogre::v1::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Constructor & Destructor Documentation
DefaultHardwareIndexBuffer()
Ogre::v1::DefaultHardwareIndexBuffer::DefaultHardwareIndexBuffer (IndexType idxType, size_t numIndexes, HardwareBuffer::Usage usage)
~DefaultHardwareIndexBuffer()
Ogre::v1::DefaultHardwareIndexBuffer::~DefaultHardwareIndexBuffer () override
Member Function Documentation
_updateFromShadow()
virtual void Ogre::v1::HardwareBuffer::_updateFromShadow () inline virtual inherited
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
copyData() [1/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References Ogre::v1::HardwareBuffer::getSizeInBytes().
copyData() [2/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) inline virtual inherited
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::D3D11HardwareIndexBuffer, Ogre::v1::D3D11HardwareVertexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
References Ogre::v1::HardwareBuffer::lock(), and Ogre::v1::HardwareBuffer::unlock().
getIndexSize()
size_t Ogre::v1::HardwareIndexBuffer::getIndexSize () const inline inherited
Get the size in bytes of each index.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
getManager()
HardwareBufferManagerBase * Ogre::v1::HardwareIndexBuffer::getManager () const inline inherited
Return the manager of this buffer, if any.
getNumIndexes()
size_t Ogre::v1::HardwareIndexBuffer::getNumIndexes () const inline inherited
Get the number of indexes in this buffer.
getRenderSystemData()
virtual void * Ogre::v1::HardwareBuffer::getRenderSystemData () inline virtual inherited
An internal function that should be used only by a render system for internal use.
Reimplemented in Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::VulkanHardwareIndexBuffer, and Ogre::v1::VulkanHardwareVertexBuffer.
getSizeInBytes()
size_t Ogre::v1::HardwareBuffer::getSizeInBytes () const inline inherited
Returns the size of this buffer in bytes.
Referenced by Ogre::v1::HardwareBuffer::copyData().
getType()
IndexType Ogre::v1::HardwareIndexBuffer::getType () const inline inherited
Get the type of indexes used in this buffer.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
getUsage()
Usage Ogre::v1::HardwareBuffer::getUsage () const inline inherited
Returns the Usage flags with which this buffer was created.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
hasShadowBuffer()
bool Ogre::v1::HardwareBuffer::hasShadowBuffer () const inline inherited
Returns whether this buffer has a system memory shadow for quicker reading.
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
isLocked()
bool Ogre::v1::HardwareBuffer::isLocked () const inline inherited
Returns whether or not this buffer is currently locked.
References Ogre::v1::HardwareBuffer::isLocked().
Referenced by Ogre::v1::HardwareBuffer::isLocked(), and Ogre::v1::HardwareBuffer::unlock().
isSystemMemory()
bool Ogre::v1::HardwareBuffer::isSystemMemory () const inline inherited
Returns whether this buffer is held in system memory.
lock() [1/2]
void * Ogre::v1::HardwareBuffer::lock (LockOptions options) inline inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
References Ogre::v1::HardwareBuffer::lock().
Referenced by Ogre::v1::HardwareBuffer::lock().
lock() [2/2]
void * Ogre::v1::DefaultHardwareIndexBuffer::lock (size_t offset, size_t length, LockOptions options) override virtual
Override HardwareBuffer to turn off all shadowing.
Reimplemented from Ogre::v1::HardwareBuffer.
readData()
void Ogre::v1::DefaultHardwareIndexBuffer::readData (size_t offset, size_t length, void * pDest) override virtual
See HardwareBuffer.
Implements Ogre::v1::HardwareBuffer.
suppressHardwareUpdate()
void Ogre::v1::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline inherited
Pass true to suppress hardware upload of shadow buffer changes.
unlock()
void Ogre::v1::DefaultHardwareIndexBuffer::unlock () override virtual
Override HardwareBuffer to turn off all shadowing.
Reimplemented from Ogre::v1::HardwareBuffer.
writeData()
void Ogre::v1::DefaultHardwareIndexBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) override virtual
See HardwareBuffer.
Implements Ogre::v1::HardwareBuffer.
Member Data Documentation
IT_16BIT
const IndexType Ogre::v1::HardwareIndexBuffer::IT_16BIT = Ogre::IT_16BIT static inherited
Referenced by Ogre::VerticesRemapInfo::performIndexDataRemap().
IT_32BIT
const IndexType Ogre::v1::HardwareIndexBuffer::IT_32BIT = Ogre::IT_32BIT static inherited
Referenced by Ogre::VerticesRemapInfo::markUsedIndices(), and Ogre::VerticesRemapInfo::performIndexDataRemap().
The documentation for this class was generated from the following file:
OgreDefaultHardwareBufferManager.h