OGRE-Next: Ogre::EllipsoidEmitter Class Reference
Ogre::EllipsoidEmitter Class Reference
Particle emitter which emits particles randomly from points inside an ellipsoid.
#include <OgreEllipsoidEmitter.h>
Public Types
enum ParticleType { Visual , Emitter }
Type of particle.
Public Member Functions
EllipsoidEmitter (ParticleSystem *psys)
See AreaEmitter.
unsigned short _getEmissionCount (Real timeElapsed) override
See ParticleEmitter.
void _initParticle (Particle *pParticle) override
See ParticleEmitter.
void _notifyOwner (ParticleSystem *owner)
Internal method for notifying the particle of it's owner.
void _notifyVisualData (ParticleVisualData *vis)
Internal method for notifying the particle of it's optional visual data.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual const Radian & getAngle () const
Returns the maximum angle which the initial particle direction can deviate from the emitters base direction.
virtual const ColourValue & getColour () const
Gets the colour of particles to be emitted.
virtual const ColourValue & getColourRangeEnd () const
Gets the maximum colour of particles to be emitted.
virtual const ColourValue & getColourRangeStart () const
Gets the minimum colour of particles to be emitted.
Real getDepth () const
Gets the depth (local y size) of the emitter.
virtual const Vector3 & getDirection () const
Returns the base direction of the emitter.
virtual const Vector3 & getDirPositionReference () const
Returns the position reference to generate direction of emitted particles.
virtual bool getDirPositionReferenceEnabled () const
Returns whether direction or position reference is used.
virtual Real getDuration () const
Gets the duration of the emitter from when it is created or re-enabled.
virtual Real getEmissionRate () const
Returns the emission rate set for this emitter.
const String & getEmittedEmitter () const
Returns the name of the emitter to be emitted.
virtual bool getEnabled () const
Gets the flag indicating if this emitter is enabled or not.
Real getHeight () const
Gets the height (local y size) of the emitter.
virtual Real getMaxDuration () const
Gets the maximum duration of this emitter in seconds (see setDuration for more details)
virtual Real getMaxParticleVelocity () const
Returns the maximum particle velocity.
virtual Real getMaxRepeatDelay () const
Gets the maximum duration of this emitter in seconds (see setRepeatDelay for more details)
virtual Real getMaxTimeToLive () const
Gets the maximum time each particle will live for.
virtual Real getMinDuration () const
Gets the minimum duration of this emitter in seconds (see setDuration for more details)
virtual Real getMinParticleVelocity () const
Returns the minimum particle velocity.
virtual Real getMinRepeatDelay () const
Gets the minimum duration of this emitter in seconds (see setRepeatDelay for more details)
virtual Real getMinTimeToLive () const
Gets the minimum time each particle will live for.
const String & getName () const
Returns the name of the emitter.
Real getOwnHeight () const
Retrieves the particle's personal width, if hasOwnDimensions is true.
Real getOwnWidth () const
Retrieves the particle's personal width, if hasOwnDimensions is true.
ParamDictionary * getParamDictionary ()
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary () const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters () const
Retrieves a list of parameters valid for this object.
virtual Real getParticleVelocity () const
Returns the initial velocity of particles emitted.
virtual const Vector3 & getPosition () const
Returns the position of this emitter relative to the center of the particle system.
virtual Real getRepeatDelay () const
Gets the duration of the emitter from when it is created or re-enabled.
const Radian & getRotation () const
virtual Real getStartTime () const
Gets the start time of the emitter.
virtual Real getTimeToLive () const
Gets the time each particle will live for.
const String & getType () const
Returns the name of the type of emitter.
virtual const Vector3 & getUp () const
Returns the up vector of the emitter.
ParticleVisualData * getVisualData () const
Get the optional visual data associated with the class.
Real getWidth () const
Gets the width (local x size) of the emitter.
bool hasOwnDimensions () const
Returns true if this particle deviates from the ParticleSystem's default dimensions (i.e.
virtual bool isEmitted () const
Return true if the emitter is emitted by another emitter.
void resetDimensions ()
Utility method to reset this particle.
virtual void setAngle (const Radian &angle)
Sets the maximum angle away from the emitter direction which particle will be emitted.
virtual void setColour (const ColourValue &colour)
Sets the initial colour of particles emitted.
virtual void setColour (const ColourValue &colourStart, const ColourValue &colourEnd)
Sets the range of colours for emitted particles.
virtual void setColourRangeEnd (const ColourValue &colour)
Sets the maximum colour of particles to be emitted.
virtual void setColourRangeStart (const ColourValue &colour)
Sets the minimum colour of particles to be emitted.
void setDepth (Real Depth)
Sets the depth (local y size) of the emitter.
void setDimensions (Real width, Real height)
Sets the width and height for this particle.
void setDirection (const Vector3 &direction) override
Overloaded to update the trans.
virtual void setDirPositionReference (const Vector3 &position, bool enable)
Sets the direction of the emitter.
virtual void setDuration (Real duration)
Sets the duration of the emitter.
virtual void setDuration (Real min, Real max)
Sets the range of random duration for this emitter.
virtual void setEmissionRate (Real particlesPerSecond)
Sets the emission rate for this emitter.
virtual void setEmitted (bool emitted)
Set the indication (true/false) to indicate that the emitter is emitted by another emitter.
virtual void setEmittedEmitter (const String &emittedEmitter)
Sets the name of the emitter to be emitted.
virtual void setEnabled (bool enabled)
Sets whether or not the emitter is enabled.
void setHeight (Real Height)
Sets the height (local y size) of the emitter.
virtual void setMaxDuration (Real max)
Sets the maximum duration of this emitter in seconds (see setDuration for more details)
virtual void setMaxParticleVelocity (Real max)
Returns the maximum particle velocity.
virtual void setMaxRepeatDelay (Real max)
Sets the maximum duration of this emitter in seconds (see setRepeatDelay for more details)
virtual void setMaxTimeToLive (Real max)
Sets the maximum time each particle will live for.
virtual void setMinDuration (Real min)
Sets the minimum duration of this emitter in seconds (see setDuration for more details)
virtual void setMinParticleVelocity (Real min)
Returns the minimum particle velocity.
virtual void setMinRepeatDelay (Real min)
Sets the minimum duration of this emitter in seconds (see setRepeatDelay for more details)
virtual void setMinTimeToLive (Real min)
Sets the minimum time each particle will live for.
virtual void setName (const String &newName)
Sets the name of the emitter.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setParticleVelocity (Real min, Real max)
Sets the initial velocity range of particles emitted.
virtual void setParticleVelocity (Real speed)
Sets the initial velocity of particles emitted.
virtual void setPosition (const Vector3 &pos)
Sets the position of this emitter relative to the particle system center.
virtual void setRepeatDelay (Real duration)
Sets the time between repeats of the emitter.
virtual void setRepeatDelay (Real min, Real max)
Sets the range of random duration for this emitter.
void setRotation (const Radian &rad)
Sets the current rotation.
void setSize (const Vector3 &size)
Sets the size of the area from which particles are emitted.
void setSize (Real x, Real y, Real z)
Sets the size of the area from which particles are emitted.
virtual void setStartTime (Real startTime)
Sets the 'start time' of this emitter.
virtual void setTimeToLive (Real minTtl, Real maxTtl)
Sets the range of lifetime for particles emitted.
virtual void setTimeToLive (Real ttl)
Sets the lifetime of all particles emitted.
virtual void setUp (const Vector3 &up)
Sets the notional up vector of the emitter.
void setWidth (Real width)
Sets the width (local x size) of the emitter.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
ColourValue mColour
Current colour.
Real mHeight
Personal height if mOwnDimensions == true.
bool mOwnDimensions
Does this particle have it's own dimensions?
ParticleType mParticleType
Determines the type of particle.
Radian mRotation
Current rotation value.
Radian mRotationSpeed
Speed of rotation in radians/sec.
Real mTimeToLive
Time to live, number of seconds left of particles natural life.
Real mTotalTimeToLive
Total Time to live, number of seconds of particles natural life.
Real mWidth
Personal width if mOwnDimensions == true.
Detailed Description
Particle emitter which emits particles randomly from points inside an ellipsoid.
Remarks
This basic particle emitter emits particles from a ellipsoid area. The initial direction of these particles can either be a single direction (i.e. a line), a random scattering inside a cone, or a random scattering in all directions, depending the 'angle' parameter, which is the angle across which to scatter the particles either side of the base direction of the emitter.
Member Enumeration Documentation
ParticleType
enum Ogre::Particle::ParticleType inherited
Type of particle.
Enumerator
Visual
Emitter
Constructor & Destructor Documentation
EllipsoidEmitter()
Ogre::EllipsoidEmitter::EllipsoidEmitter (ParticleSystem * psys)
See AreaEmitter.
Member Function Documentation
_getEmissionCount()
unsigned short Ogre::AreaEmitter::_getEmissionCount (Real timeElapsed) override virtual inherited
See ParticleEmitter.
Implements Ogre::ParticleEmitter.
_initParticle()
void Ogre::EllipsoidEmitter::_initParticle (Particle * pParticle) override virtual
See ParticleEmitter.
Reimplemented from Ogre::ParticleEmitter.
Reimplemented in Ogre::HollowEllipsoidEmitter.
_notifyOwner()
void Ogre::Particle::_notifyOwner (ParticleSystem * owner) inherited
Internal method for notifying the particle of it's owner.
_notifyVisualData()
void Ogre::Particle::_notifyVisualData (ParticleVisualData * vis) inline inherited
Internal method for notifying the particle of it's optional visual data.
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
getAngle()
virtual const Radian & Ogre::ParticleEmitter::getAngle () const virtual inherited
Returns the maximum angle which the initial particle direction can deviate from the emitters base direction.
getColour()
virtual const ColourValue & Ogre::ParticleEmitter::getColour () const virtual inherited
Gets the colour of particles to be emitted.
getColourRangeEnd()
virtual const ColourValue & Ogre::ParticleEmitter::getColourRangeEnd () const virtual inherited
Gets the maximum colour of particles to be emitted.
getColourRangeStart()
virtual const ColourValue & Ogre::ParticleEmitter::getColourRangeStart () const virtual inherited
Gets the minimum colour of particles to be emitted.
getDepth()
Real Ogre::AreaEmitter::getDepth () const inherited
Gets the depth (local y size) of the emitter.
getDirection()
virtual const Vector3 & Ogre::ParticleEmitter::getDirection () const virtual inherited
Returns the base direction of the emitter.
getDirPositionReference()
virtual const Vector3 & Ogre::ParticleEmitter::getDirPositionReference () const virtual inherited
Returns the position reference to generate direction of emitted particles.
getDirPositionReferenceEnabled()
virtual bool Ogre::ParticleEmitter::getDirPositionReferenceEnabled () const virtual inherited
Returns whether direction or position reference is used.
getDuration()
virtual Real Ogre::ParticleEmitter::getDuration () const virtual inherited
Gets the duration of the emitter from when it is created or re-enabled.
getEmissionRate()
virtual Real Ogre::ParticleEmitter::getEmissionRate () const virtual inherited
Returns the emission rate set for this emitter.
getEmittedEmitter()
const String & Ogre::ParticleEmitter::getEmittedEmitter () const inherited
Returns the name of the emitter to be emitted.
getEnabled()
virtual bool Ogre::ParticleEmitter::getEnabled () const virtual inherited
Gets the flag indicating if this emitter is enabled or not.
getHeight()
Real Ogre::AreaEmitter::getHeight () const inherited
Gets the height (local y size) of the emitter.
getMaxDuration()
virtual Real Ogre::ParticleEmitter::getMaxDuration () const virtual inherited
Gets the maximum duration of this emitter in seconds (see setDuration for more details)
getMaxParticleVelocity()
virtual Real Ogre::ParticleEmitter::getMaxParticleVelocity () const virtual inherited
Returns the maximum particle velocity.
getMaxRepeatDelay()
virtual Real Ogre::ParticleEmitter::getMaxRepeatDelay () const virtual inherited
Gets the maximum duration of this emitter in seconds (see setRepeatDelay for more details)
getMaxTimeToLive()
virtual Real Ogre::ParticleEmitter::getMaxTimeToLive () const virtual inherited
Gets the maximum time each particle will live for.
getMinDuration()
virtual Real Ogre::ParticleEmitter::getMinDuration () const virtual inherited
Gets the minimum duration of this emitter in seconds (see setDuration for more details)
getMinParticleVelocity()
virtual Real Ogre::ParticleEmitter::getMinParticleVelocity () const virtual inherited
Returns the minimum particle velocity.
getMinRepeatDelay()
virtual Real Ogre::ParticleEmitter::getMinRepeatDelay () const virtual inherited
Gets the minimum duration of this emitter in seconds (see setRepeatDelay for more details)
getMinTimeToLive()
virtual Real Ogre::ParticleEmitter::getMinTimeToLive () const virtual inherited
Gets the minimum time each particle will live for.
getName()
const String & Ogre::ParticleEmitter::getName () const inherited
Returns the name of the emitter.
getOwnHeight()
Real Ogre::Particle::getOwnHeight () const inline inherited
Retrieves the particle's personal width, if hasOwnDimensions is true.
getOwnWidth()
Real Ogre::Particle::getOwnWidth () const inline inherited
Retrieves the particle's personal width, if hasOwnDimensions is true.
getParamDictionary() [1/2]
ParamDictionary * Ogre::StringInterface::getParamDictionary () inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary * Ogre::StringInterface::getParamDictionary () const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList & Ogre::StringInterface::getParameters () const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getParticleVelocity()
virtual Real Ogre::ParticleEmitter::getParticleVelocity () const virtual inherited
Returns the initial velocity of particles emitted.
getPosition()
virtual const Vector3 & Ogre::ParticleEmitter::getPosition () const virtual inherited
Returns the position of this emitter relative to the center of the particle system.
getRepeatDelay()
virtual Real Ogre::ParticleEmitter::getRepeatDelay () const virtual inherited
Gets the duration of the emitter from when it is created or re-enabled.
getRotation()
const Radian & Ogre::Particle::getRotation () const inline inherited
getStartTime()
virtual Real Ogre::ParticleEmitter::getStartTime () const virtual inherited
Gets the start time of the emitter.
getTimeToLive()
virtual Real Ogre::ParticleEmitter::getTimeToLive () const virtual inherited
Gets the time each particle will live for.
getType()
const String & Ogre::ParticleEmitter::getType () const inline inherited
Returns the name of the type of emitter.
Remarks
This property is useful for determining the type of emitter procedurally so another can be created.
getUp()
virtual const Vector3 & Ogre::ParticleEmitter::getUp () const virtual inherited
Returns the up vector of the emitter.
getVisualData()
ParticleVisualData * Ogre::Particle::getVisualData () const inline inherited
Get the optional visual data associated with the class.
getWidth()
Real Ogre::AreaEmitter::getWidth () const inherited
Gets the width (local x size) of the emitter.
hasOwnDimensions()
bool Ogre::Particle::hasOwnDimensions () const inline inherited
Returns true if this particle deviates from the ParticleSystem's default dimensions (i.e.
if the particle::setDimensions method has been called for this instance).
See also
particle::setDimensions
isEmitted()
virtual bool Ogre::ParticleEmitter::isEmitted () const virtual inherited
Return true if the emitter is emitted by another emitter.
resetDimensions()
void Ogre::Particle::resetDimensions () inherited
Utility method to reset this particle.
Referenced by Ogre::ParticleEmitter::_initParticle().
setAngle()
virtual void Ogre::ParticleEmitter::setAngle (const Radian & angle) virtual inherited
Sets the maximum angle away from the emitter direction which particle will be emitted.
Remarks
Whilst the direction property defines the general direction of emission for particles, this property defines how far the emission angle can deviate away from this base direction. This allows you to create a scatter effect - if set to 0, all particles will be emitted exactly along the emitters direction vector, whereas if you set it to 180 degrees or more, particles will be emitted in a sphere, i.e. in all directions.
Parameters
angle Maximum angle which initial particle direction can deviate from the emitter base direction vector.
setColour() [1/2]
virtual void Ogre::ParticleEmitter::setColour (const ColourValue & colour) virtual inherited
Sets the initial colour of particles emitted.
Remarks
Particles have an initial colour on emission which the emitter sets. This method sets this colour. See the alternate version of this method which takes 2 colours in order to establish a range of colours to be assigned to particles.
Parameters
colour The colour which all particles will be given on emission.
setColour() [2/2]
virtual void Ogre::ParticleEmitter::setColour (const ColourValue & colourStart, const ColourValue & colourEnd) virtual inherited
Sets the range of colours for emitted particles.
Remarks
Particles have an initial colour on emission which the emitter sets. This method sets the range of this colour. See the alternate version of this method which takes a single colour in order to set a constant colour for all particles. Emitters may choose to randomly assign a colour in this range, or may use some other method to vary the colour.
Parameters
colourStart The start of the colour range
colourEnd The end of the colour range
setColourRangeEnd()
virtual void Ogre::ParticleEmitter::setColourRangeEnd (const ColourValue & colour) virtual inherited
Sets the maximum colour of particles to be emitted.
setColourRangeStart()
virtual void Ogre::ParticleEmitter::setColourRangeStart (const ColourValue & colour) virtual inherited
Sets the minimum colour of particles to be emitted.
setDepth()
void Ogre::AreaEmitter::setDepth (Real Depth) inherited
Sets the depth (local y size) of the emitter.
setDimensions()
void Ogre::Particle::setDimensions (Real width, Real height) inherited
Sets the width and height for this particle.
Remarks
Note that it is most efficient for every particle in a ParticleSystem to have the same dimensions. If you choose to alter the dimensions of an individual particle the set will be less efficient. Do not call this method unless you really need to have different particle dimensions within the same set. Otherwise just call the ParticleSystem::setDefaultDimensions method instead.
setDirection()
void Ogre::AreaEmitter::setDirection (const Vector3 & direction) override virtual inherited
Overloaded to update the trans.
matrix
Reimplemented from Ogre::ParticleEmitter.
setDirPositionReference()
virtual void Ogre::ParticleEmitter::setDirPositionReference (const Vector3 & position, bool enable) virtual inherited
Sets the direction of the emitter.
Some particle effects need to emit particles in many random directions, but still following some rules; like not having them collide against each other. Very useful for explosions and implosions (when velocity is negative)
Note
Although once enabled mDirPositionRef will supersede mDirection; calling setDirection() may still be needed to setup a custom up vector.
Parameters
position The reference position in which the direction of the particles will be calculated from, also taking into account the particle's position at the time of emission.
enable True to use mDirPositionRef, false to use the default behaviour with mDirection
setDuration() [1/2]
virtual void Ogre::ParticleEmitter::setDuration (Real duration) virtual inherited
Sets the duration of the emitter.
Remarks
By default emitters run indefinitely (unless you manually disable them). By setting this parameter, you can make an emitter turn off on it's own after a set number of seconds. It will then remain disabled until either setEnabled(true) is called, or if the 'repeatAfter' parameter has been set it will also repeat after a number of seconds.
Also see the alternative version of this method which allows you to set a min and max duration for a random variable duration.
Parameters
duration The duration in seconds.
setDuration() [2/2]
virtual void Ogre::ParticleEmitter::setDuration (Real min, Real max) virtual inherited
Sets the range of random duration for this emitter.
Remarks
By default emitters run indefinitely (unless you manually disable them). By setting this parameter, you can make an emitter turn off on it's own after a random number of seconds. It will then remain disabled until either setEnabled(true) is called, or if the 'repeatAfter' parameter has been set it will also repeat after a number of seconds.
Also see the alternative version of this method which allows you to set a constant duration.
Parameters
min The minimum duration in seconds.
max The minimum duration in seconds.
setEmissionRate()
virtual void Ogre::ParticleEmitter::setEmissionRate (Real particlesPerSecond) virtual inherited
Sets the emission rate for this emitter.
Remarks
This method tells the emitter how many particles per second should be emitted. The emitter subclass does not have to emit these in a continuous burst - this is a relative parameter and the emitter may choose to emit all of the second's worth of particles every half-second for example. This is controlled by the emitter's getEmissionCount method.
Also, if the ParticleSystem's particle quota is exceeded, not all the particles requested may be actually emitted.
Parameters
particlesPerSecond The number of particles to be emitted every second.
setEmitted()
virtual void Ogre::ParticleEmitter::setEmitted (bool emitted) virtual inherited
Set the indication (true/false) to indicate that the emitter is emitted by another emitter.
setEmittedEmitter()
virtual void Ogre::ParticleEmitter::setEmittedEmitter (const String & emittedEmitter) virtual inherited
Sets the name of the emitter to be emitted.
setEnabled()
virtual void Ogre::ParticleEmitter::setEnabled (bool enabled) virtual inherited
Sets whether or not the emitter is enabled.
Remarks
You can turn an emitter off completely by setting this parameter to false.
setHeight()
void Ogre::AreaEmitter::setHeight (Real Height) inherited
Sets the height (local y size) of the emitter.
setMaxDuration()
virtual void Ogre::ParticleEmitter::setMaxDuration (Real max) virtual inherited
Sets the maximum duration of this emitter in seconds (see setDuration for more details)
setMaxParticleVelocity()
virtual void Ogre::ParticleEmitter::setMaxParticleVelocity (Real max) virtual inherited
Returns the maximum particle velocity.
setMaxRepeatDelay()
virtual void Ogre::ParticleEmitter::setMaxRepeatDelay (Real max) virtual inherited
Sets the maximum duration of this emitter in seconds (see setRepeatDelay for more details)
setMaxTimeToLive()
virtual void Ogre::ParticleEmitter::setMaxTimeToLive (Real max) virtual inherited
Sets the maximum time each particle will live for.
Must be non-negative!
setMinDuration()
virtual void Ogre::ParticleEmitter::setMinDuration (Real min) virtual inherited
Sets the minimum duration of this emitter in seconds (see setDuration for more details)
setMinParticleVelocity()
virtual void Ogre::ParticleEmitter::setMinParticleVelocity (Real min) virtual inherited
Returns the minimum particle velocity.
setMinRepeatDelay()
virtual void Ogre::ParticleEmitter::setMinRepeatDelay (Real min) virtual inherited
Sets the minimum duration of this emitter in seconds (see setRepeatDelay for more details)
setMinTimeToLive()
virtual void Ogre::ParticleEmitter::setMinTimeToLive (Real min) virtual inherited
Sets the minimum time each particle will live for.
Must be non-negative!
setName()
virtual void Ogre::ParticleEmitter::setName (const String & newName) virtual inherited
Sets the name of the emitter.
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setParticleVelocity() [1/2]
virtual void Ogre::ParticleEmitter::setParticleVelocity (Real min, Real max) virtual inherited
Sets the initial velocity range of particles emitted.
Remarks
This method sets the range of starting speeds for emitted particles. See the alternate version of this method which takes 1 parameter if you want a constant speed. This emitter will randomly choose a speed between the minimum and maximum for each particle.
Parameters
max The maximum speed in world units per second for the initial particle speed on emission.
min The minimum speed in world units per second for the initial particle speed on emission.
setParticleVelocity() [2/2]
virtual void Ogre::ParticleEmitter::setParticleVelocity (Real speed) virtual inherited
Sets the initial velocity of particles emitted.
Remarks
This method sets a constant speed for emitted particles. See the alternate version of this method which takes 2 parameters if you want a variable speed.
Parameters
speed The initial speed in world units per second which every particle emitted starts with.
setPosition()
virtual void Ogre::ParticleEmitter::setPosition (const Vector3 & pos) virtual inherited
Sets the position of this emitter relative to the particle system center.
setRepeatDelay() [1/2]
virtual void Ogre::ParticleEmitter::setRepeatDelay (Real duration) virtual inherited
Sets the time between repeats of the emitter.
Remarks
By default emitters run indefinitely (unless you manually disable them). However, if you manually disable the emitter (by calling setEnabled(false), or it's duration runs out, it will cease to emit
Also see the alternative version of this method which allows you to set a min and max duration for a random variable duration.
Parameters
duration The duration in seconds.
setRepeatDelay() [2/2]
virtual void Ogre::ParticleEmitter::setRepeatDelay (Real min, Real max) virtual inherited
Sets the range of random duration for this emitter.
Remarks
By default emitters run indefinitely (unless you manually disable them). By setting this parameter, you can make an emitter turn off on it's own after a random number of seconds. It will then remain disabled until either setEnabled(true) is called, or if the 'repeatAfter' parameter has been set it will also repeat after a number of seconds.
Also see the alternative version of this method which allows you to set a constant duration.
Parameters
min The minimum duration in seconds.
max The minimum duration in seconds.
setRotation()
void Ogre::Particle::setRotation (const Radian & rad) inherited
Sets the current rotation.
setSize() [1/2]
void Ogre::AreaEmitter::setSize (const Vector3 & size) inherited
Sets the size of the area from which particles are emitted.
Parameters
size Vector describing the size of the area. The area extends around the center point by half the x, y and z components of this vector. The box is aligned such that it's local Z axis points along it's direction (see setDirection)
setSize() [2/2]
void Ogre::AreaEmitter::setSize (Real x, Real y, Real z) inherited
Sets the size of the area from which particles are emitted.
Parameters
x,y,z Individual axis lengths describing the size of the area. The area extends around the center point by half the x, y and z components of this vector. The box is aligned such that it's local Z axis points along it's direction (see setDirection)
setStartTime()
virtual void Ogre::ParticleEmitter::setStartTime (Real startTime) virtual inherited
Sets the 'start time' of this emitter.
Remarks
By default an emitter starts straight away as soon as a ParticleSystem is first created, or also just after it is re-enabled. This parameter allows you to set a time delay so that the emitter does not 'kick in' until later.
Parameters
startTime The time in seconds from the creation or enabling of the emitter.
setTimeToLive() [1/2]
virtual void Ogre::ParticleEmitter::setTimeToLive (Real minTtl, Real maxTtl) virtual inherited
Sets the range of lifetime for particles emitted.
Remarks
The emitter initialises particles with a time-to-live (TTL), the number of seconds a particle will exist before being destroyed. This method sets a range for the TTL for all particles emitted; the ttl may be randomised between these 2 extremes or will vary some other way depending on the emitter. Note that affectors are able to modify the TTL of particles later.
Also see the alternate version of this method which takes a single TTL in order to set a constant TTL for all particles.
Parameters
minTtl The minimum number of seconds each particle will live for. Must be non-negative!
maxTtl The maximum number of seconds each particle will live for. Must be non-negative!
setTimeToLive() [2/2]
virtual void Ogre::ParticleEmitter::setTimeToLive (Real ttl) virtual inherited
Sets the lifetime of all particles emitted.
Remarks
The emitter initialises particles with a time-to-live (TTL), the number of seconds a particle will exist before being destroyed. This method sets a constant TTL for all particles emitted. Note that affectors are able to modify the TTL of particles later.
Also see the alternate version of this method which takes a min and max TTL in order to have the TTL vary per particle.
Parameters
ttl The number of seconds each particle will live for.
setUp()
virtual void Ogre::ParticleEmitter::setUp (const Vector3 & up) virtual inherited
Sets the notional up vector of the emitter.
Remarks
Many emitters emit particles from within a region, and for some that region is not circularly symmetric about the emitter direction. The up vector allows such emitters to be orientated about the direction vector.
Parameters
up The base direction for particles emitted. It must be perpendicular to the direction vector.
setWidth()
void Ogre::AreaEmitter::setWidth (Real width) inherited
Sets the width (local x size) of the emitter.
Member Data Documentation
mColour
ColourValue Ogre::Particle::mColour inherited
Current colour.
mHeight
Real Ogre::Particle::mHeight inherited
Personal height if mOwnDimensions == true.
mOwnDimensions
bool Ogre::Particle::mOwnDimensions inherited
Does this particle have it's own dimensions?
mParticleType
ParticleType Ogre::Particle::mParticleType inherited
Determines the type of particle.
mRotation
Radian Ogre::Particle::mRotation inherited
Current rotation value.
mRotationSpeed
Radian Ogre::Particle::mRotationSpeed inherited
Speed of rotation in radians/sec.
mTimeToLive
Real Ogre::Particle::mTimeToLive inherited
Time to live, number of seconds left of particles natural life.
mTotalTimeToLive
Real Ogre::Particle::mTotalTimeToLive inherited
Total Time to live, number of seconds of particles natural life.
mWidth
Real Ogre::Particle::mWidth inherited
Personal width if mOwnDimensions == true.
The documentation for this class was generated from the following file:
OgreEllipsoidEmitter.h