OGRE-Next: Ogre::D3D11HLSLProgram Class Reference
Ogre::D3D11HLSLProgram Class Reference final
Specialization of HighLevelGpuProgram to provide support for D3D11 High-Level Shader Language (HLSL).
#include <OgreD3D11HLSLProgram.h>
Classes
class CmdColumnMajorMatrices
Command object for setting matrix packing in column-major order.
class CmdEnableBackwardsCompatibility
Command object for setting backwards compatibility.
class CmdEntryPoint
Command object for setting entry point.
class CmdPreprocessorDefines
Command object for setting macro defines.
class CmdTarget
Command object for setting target assembler.
Public Types
enum LoadingFlags {
LF_DEFAULT = 0 , LF_INCLUDE_NON_RELOADABLE = 1 , LF_ONLY_UNREFERENCED = 2 , LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3 ,
LF_PRESERVE_STATE = 4 , LF_MARKED_FOR_RELOAD = 8
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED , LOADSTATE_LOADING , LOADSTATE_LOADED , LOADSTATE_UNLOADING ,
LOADSTATE_PREPARED , LOADSTATE_PREPARING , LOADSTATE_UNLOADED_MARKED_FOR_RELOAD
}
Enum identifying the loading state of the resource.
Public Member Functions
D3D11HLSLProgram (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual, ManualResourceLoader *loader, D3D11Device &device)
~D3D11HLSLProgram () override
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete ()
Firing of unloading complete event.
GpuProgram * _getBindingDelegate () override
Returns the GpuProgram which should be bound to the pipeline.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
void buildConstantDefinitions () const override
Build the constant definition map, must be overridden.
size_t calculateSize () const override
Calculate the size of a resource; this will only be called after 'load'.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
void CreateComputeShader ()
void CreateDomainShader ()
void CreateGeometryShader ()
void CreateHullShader ()
GpuProgramParametersSharedPtr createParameters () override
Overridden from GpuProgram.
void CreatePixelShader ()
void CreateVertexShader ()
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
bool getBuildParametersFromReflection () const
bool getColumnMajorMatrices () const
Gets whether matrix packed in column-major order.
const String & getCompatibleTarget () const
Gets the shader target promoted to the first compatible, e.g.
virtual Vector3 getComputeGroupDimensions () const
Returns the number of process groups dispatched by this compute program.
ID3D11ComputeShader * getComputeShader () const
void getConstantBuffers (ID3D11Buffer **buffers, UINT &outSlotStart, UINT &outNumBuffers, GpuProgramParametersSharedPtr params, uint16 variabilityMask)
buffers must have a capacity of 2, i.e. ID3D11Buffer *buffers[2];
const GpuNamedConstants & getConstantDefinitions () const override
Get the full list of GpuConstantDefinition instances.
virtual ResourceManager * getCreator ()
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr getDefaultParameters ()
Get a reference to the default parameters which are to be used for all uses of this program.
ID3D11DomainShader * getDomainShader () const
bool getEnableBackwardsCompatibility () const
Gets whether backwards compatibility is enabled.
bool getEnableIncludeHeader () const
const String & getEntryPoint () const
Gets the entry point defined for this program.
ID3D11GeometryShader * getGeometryShader () const
virtual const String & getGroup () const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle () const
ID3D11HullShader * getHullShader () const
const D3D11_SIGNATURE_PARAMETER_DESC & getInputParamDesc (size_t index) const
const String & getLanguage () const override
Overridden from GpuProgram.
ComPtr< ID3D11InputLayout > getLayoutForPso (const VertexElement2VecVec &vertexElements)
virtual LoadingState getLoadingState () const
Returns the current loading state.
virtual const String & getManualNamedConstantsFile () const
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
const MicroCode & getMicroCode () const
virtual const String & getName () const
Gets resource name.
String getNameForMicrocodeCache ()
virtual ushort getNumberOfPosesIncluded () const
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
uint8 getNumClipDistances () const
Retrieves the number of clip distances. See GpuProgram::setNumClipDistances.
size_t getNumInputs () const
size_t getNumOutputs () const
virtual const String & getOrigin () const
Get the origin of this resource, e.g.
const D3D11_SIGNATURE_PARAMETER_DESC & getOutputParamDesc (size_t index) const
ParamDictionary * getParamDictionary ()
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary () const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters () const
Retrieves a list of parameters valid for this object.
virtual bool getPassFogStates () const
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
virtual bool getPassSurfaceAndLightStates () const
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
virtual bool getPassTransformStates () const
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
ID3D11PixelShader * getPixelShader () const
const String & getPreprocessorDefines () const
Sets the preprocessor defines use to compile the program.
virtual size_t getSize () const
Retrieves info about the size of the resource.
virtual const String & getSource () const
Gets the assembler source for this program.
virtual const String & getSourceFile () const
Gets the name of the file used as source for this program.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
unsigned int getSubroutineSlot (const String &subroutineSlotName) const
virtual const String & getSyntaxCode () const
Gets the syntax code for this program e.g.
const String & getTarget () const
Gets the shader target to compile down to, e.g.
virtual GpuProgramType getType () const
Get the program type.
bool getUseHlmsParser () const
ID3D11VertexShader * getVertexShader () const
virtual bool hasCompileError () const
Did this program encounter a compile error when loading?
virtual bool hasDefaultParameters () const
Returns true if default parameters have been set up.
virtual bool isAdjacencyInfoRequired () const
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool isBackgroundLoaded () const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded () const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded () const
Is this resource manually loaded?
virtual bool isMorphAnimationIncluded () const
Returns whether a vertex program includes the required instructions to perform morph animation.
virtual bool isPoseAnimationIncluded () const
Returns whether a vertex program includes the required instructions to perform pose animation.
virtual bool isPrepared () const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable () const
Returns true if the Resource is reloadable, false otherwise.
virtual bool isSkeletalAnimationIncluded () const
Returns whether a vertex program includes the required instructions to perform skeletal animation.
bool isSupported () const override
Overridden from GpuProgram.
virtual bool isVertexTextureFetchRequired () const
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
virtual bool isVpAndRtArrayIndexFromAnyShaderRequired () const
Returns whether this program requires support for choosing viewport or render target index in any program or only geometry one.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
void loadFromSource () override
Internal load implementation, must be implemented by subclasses.
bool markForReload ()
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
void reinterpretGSForStreamOut ()
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void resetCompileError ()
Reset a compile error if it occurred, allowing the load to be retried.
virtual void setAdjacencyInfoRequired (bool r)
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void setAutoReflectArrayBindingsInRootLayout (bool bReflectArrayRootLayouts)
Set to true to reflects the shader looking for array bindings (e.g.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
void setBuildParametersFromReflection (bool buildParams)
void setColumnMajorMatrices (bool columnMajor)
Sets whether matrix packing in column-major order.
virtual void setComputeGroupDimensions (Vector3 dimensions)
Sets the number of process groups dispatched by this compute program.
void setEnableBackwardsCompatibility (bool enableBackwardsCompatibility)
Sets whether backwards compatibility is enabled.
void setEnableIncludeHeader (bool bEnable)
Whether we should parse the source code looking for include files and embedding the file.
void setEntryPoint (const String &entryPoint)
Sets the entry point for this program ie the first method called.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual void setManualNamedConstants (const GpuNamedConstants &namedConstants)
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
virtual void setManualNamedConstantsFile (const String &paramDefFile)
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual void setMorphAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform morph animation.
void setNumClipDistances (const uint8 numClipDistances)
Sets the number of clip distances this shader uses.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPoseAnimationIncluded (ushort poseCount)
Sets whether a vertex program includes the required instructions to perform pose animation.
void setPrefabRootLayout (const PrefabRootLayout::PrefabRootLayout &prefab)
Sets a prefab root layout, mostly meant for low level materials (e.g.
void setPreprocessorDefines (const String &defines)
Sets the preprocessor defines use to compile the program.
virtual void setReplaceVersionMacro (bool bReplace)
When true:
virtual void setRootLayout (GpuProgramType t, const RootLayout &rootLayout)
Sets a RootLayout programmatically, thus the shader source won't be parsed looking for one We will call validate()
virtual void setSkeletalAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform skeletal animation.
virtual void setSource (const String &source)
Sets the source assembly for this program from an in-memory string.
virtual void setSource (const String &source, const String &debugFilename)
Sets the source assembly for this program from an in-memory string, while providing a path to a file, which can be needed/useful for debugging shaders (i.e.
virtual void setSourceFile (const String &filename)
Sets the filename of the source assembly for this program.
virtual void setSyntaxCode (const String &syntax)
Sets the syntax code for this program e.g.
void setTarget (const String &target)
Sets the shader target to compile down to, e.g.
virtual void setToLoaded ()
Change the Resource loading state to loaded.
virtual void setType (GpuProgramType t)
Set the program type (only valid before load)
virtual void setUniformBlockBinding (const char *blockName, uint32 bindingSlot)
For GL only. Program must be bound when calling.
void setUseHlmsParser (bool bUse)
Whether we should run the shader through the Hlms parser.
virtual void setVertexTextureFetchRequired (bool r)
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void setVpAndRtArrayIndexFromAnyShaderRequired (bool r)
Sets whether this program requires support for choosing viewport or render target index in any program or only geometry one.
virtual void touch ()
'Touches' the resource to indicate it has been used.
virtual void unload ()
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
virtual void unsetRootLayout ()
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
bool mReinterpretingGS
OGRE_AUTO_MUTEX
Static Public Attributes
static CmdEnableIncludeHeader msEnableIncludeHeaderCmd
static CmdUseHlmsParser msUseHlmsParser
Detailed Description
Specialization of HighLevelGpuProgram to provide support for D3D11 High-Level Shader Language (HLSL).
Remarks
Note that the syntax of D3D11 HLSL is identical to nVidia's Cg language, therefore unless you know you will only ever be deploying on Direct3D, or you have some specific reason for not wanting to use the Cg plugin, I suggest you use Cg instead since that can produce programs for OpenGL too.
Member Enumeration Documentation
LoadingFlags
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object.
Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
LF_MARKED_FOR_RELOAD
Resources are marked for reload on unloading, and only marked ones are processed on reloading.
LoadingState
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
LOADSTATE_UNLOADED_MARKED_FOR_RELOAD
Unloaded and marked for reload.
Constructor & Destructor Documentation
D3D11HLSLProgram()
Ogre::D3D11HLSLProgram::D3D11HLSLProgram (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual, ManualResourceLoader * loader, D3D11Device & device)
~D3D11HLSLProgram()
Ogre::D3D11HLSLProgram::~D3D11HLSLProgram () override
Member Function Documentation
_dirtyState()
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
_fireLoadingComplete()
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_firePreparingComplete()
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_fireUnloadingComplete()
virtual void Ogre::Resource::_fireUnloadingComplete () virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
_getBindingDelegate()
GpuProgram * Ogre::HighLevelGpuProgram::_getBindingDelegate () inline override virtual inherited
Returns the GpuProgram which should be bound to the pipeline.
Remarks
This method is simply to allow some subclasses of GpuProgram to delegate the program which is bound to the pipeline to a delegate, if required.
Reimplemented from Ogre::GpuProgram.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLShader.
_notifyOrigin()
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
addListener()
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
buildConstantDefinitions()
void Ogre::D3D11HLSLProgram::buildConstantDefinitions () const override virtual
Build the constant definition map, must be overridden.
Note
The implementation must fill in the (inherited) mConstantDefs field at a minimum, and if the program requires that parameters are bound using logical parameter indexes then the mFloatLogicalToPhysical and mIntLogicalToPhysical maps must also be populated.
Implements Ogre::HighLevelGpuProgram.
calculateSize()
size_t Ogre::HighLevelGpuProgram::calculateSize () const override virtual inherited
Calculate the size of a resource; this will only be called after 'load'.
Reimplemented from Ogre::GpuProgram.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLShader.
changeGroupOwnership()
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
CreateComputeShader()
void Ogre::D3D11HLSLProgram::CreateComputeShader ()
CreateDomainShader()
void Ogre::D3D11HLSLProgram::CreateDomainShader ()
CreateGeometryShader()
void Ogre::D3D11HLSLProgram::CreateGeometryShader ()
CreateHullShader()
void Ogre::D3D11HLSLProgram::CreateHullShader ()
createParameters()
GpuProgramParametersSharedPtr Ogre::D3D11HLSLProgram::createParameters () override virtual
Overridden from GpuProgram.
Reimplemented from Ogre::HighLevelGpuProgram.
CreatePixelShader()
void Ogre::D3D11HLSLProgram::CreatePixelShader ()
CreateVertexShader()
void Ogre::D3D11HLSLProgram::CreateVertexShader ()
escalateLoading()
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getBuildParametersFromReflection()
bool Ogre::GpuProgram::getBuildParametersFromReflection () const inline inherited
getColumnMajorMatrices()
bool Ogre::D3D11HLSLProgram::getColumnMajorMatrices () const inline
Gets whether matrix packed in column-major order.
getCompatibleTarget()
const String & Ogre::D3D11HLSLProgram::getCompatibleTarget () const
Gets the shader target promoted to the first compatible, e.g.
'vs_4_0' or 'ps_4_0' if backward compatibility is enabled.
getComputeGroupDimensions()
virtual Vector3 Ogre::GpuProgram::getComputeGroupDimensions () const inline virtual inherited
Returns the number of process groups dispatched by this compute program.
getComputeShader()
ID3D11ComputeShader * Ogre::D3D11HLSLProgram::getComputeShader () const
getConstantBuffers()
void Ogre::D3D11HLSLProgram::getConstantBuffers (ID3D11Buffer ** buffers, UINT & outSlotStart, UINT & outNumBuffers, GpuProgramParametersSharedPtr params, uint16 variabilityMask)
buffers must have a capacity of 2, i.e. ID3D11Buffer *buffers[2];
getConstantDefinitions()
const GpuNamedConstants & Ogre::HighLevelGpuProgram::getConstantDefinitions () const override virtual inherited
Get the full list of GpuConstantDefinition instances.
Note
Only available if this parameters object has named parameters.
Reimplemented from Ogre::GpuProgram.
getCreator()
virtual ResourceManager * Ogre::Resource::getCreator () inline virtual inherited
Gets the manager which created this resource.
getDefaultParameters()
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::getDefaultParameters () virtual inherited
Get a reference to the default parameters which are to be used for all uses of this program.
Remarks
A program can be set up with a list of default parameters, which can save time when using a program many times in a material with roughly the same settings. By retrieving the default parameters and populating it with the most used options, any new parameter objects created from this program afterwards will automatically include the default parameters; thus users of the program need only change the parameters which are unique to their own usage of the program.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getDomainShader()
ID3D11DomainShader * Ogre::D3D11HLSLProgram::getDomainShader () const
getEnableBackwardsCompatibility()
bool Ogre::D3D11HLSLProgram::getEnableBackwardsCompatibility () const inline
Gets whether backwards compatibility is enabled.
getEnableIncludeHeader()
bool Ogre::HighLevelGpuProgram::getEnableIncludeHeader () const inherited
getEntryPoint()
const String & Ogre::D3D11HLSLProgram::getEntryPoint () const inline
Gets the entry point defined for this program.
getGeometryShader()
ID3D11GeometryShader * Ogre::D3D11HLSLProgram::getGeometryShader () const
getGroup()
virtual const String & Ogre::Resource::getGroup () const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::v1::OldSkeletonInstance.
getHandle()
virtual ResourceHandle Ogre::Resource::getHandle () const inline virtual inherited
Reimplemented in Ogre::v1::OldSkeletonInstance.
getHullShader()
ID3D11HullShader * Ogre::D3D11HLSLProgram::getHullShader () const
getInputParamDesc()
const D3D11_SIGNATURE_PARAMETER_DESC & Ogre::D3D11HLSLProgram::getInputParamDesc (size_t index) const
getLanguage()
const String & Ogre::D3D11HLSLProgram::getLanguage () const override virtual
Overridden from GpuProgram.
Reimplemented from Ogre::GpuProgram.
getLayoutForPso()
ComPtr< ID3D11InputLayout > Ogre::D3D11HLSLProgram::getLayoutForPso (const VertexElement2VecVec & vertexElements)
getLoadingState()
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
getManualNamedConstantsFile()
virtual const String & Ogre::GpuProgram::getManualNamedConstantsFile () const inline virtual inherited
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
getMicroCode()
const MicroCode & Ogre::D3D11HLSLProgram::getMicroCode () const
getName()
virtual const String & Ogre::Resource::getName () const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::v1::OldSkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName().
getNameForMicrocodeCache()
String Ogre::D3D11HLSLProgram::getNameForMicrocodeCache ()
getNumberOfPosesIncluded()
virtual ushort Ogre::GpuProgram::getNumberOfPosesIncluded () const inline virtual inherited
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getNumClipDistances()
uint8 Ogre::GpuProgram::getNumClipDistances () const inline inherited
Retrieves the number of clip distances. See GpuProgram::setNumClipDistances.
getNumInputs()
size_t Ogre::D3D11HLSLProgram::getNumInputs () const
getNumOutputs()
size_t Ogre::D3D11HLSLProgram::getNumOutputs () const
getOrigin()
virtual const String & Ogre::Resource::getOrigin () const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
getOutputParamDesc()
const D3D11_SIGNATURE_PARAMETER_DESC & Ogre::D3D11HLSLProgram::getOutputParamDesc (size_t index) const
getParamDictionary() [1/2]
ParamDictionary * Ogre::StringInterface::getParamDictionary () inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary * Ogre::StringInterface::getParamDictionary () const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList & Ogre::StringInterface::getParameters () const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getPassFogStates()
virtual bool Ogre::GpuProgram::getPassFogStates () const inline virtual inherited
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
Remarks
On DirectX, shader model 2 and earlier continues to have fixed-function fog applied to it, so fog state is still passed (you should disable fog on the pass if you want to perform fog in the shader). In OpenGL it is also common to be able to access the fixed-function fog state inside the shader.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLShader, Ogre::MetalProgram, and Ogre::VulkanProgram.
getPassSurfaceAndLightStates()
virtual bool Ogre::GpuProgram::getPassSurfaceAndLightStates () const inline virtual inherited
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
Remarks
Most vertex programs do not need this material information, however GLSL shaders can refer to this material and lighting state so enable this option
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLShader, Ogre::MetalProgram, and Ogre::VulkanProgram.
getPassTransformStates()
virtual bool Ogre::GpuProgram::getPassTransformStates () const inline virtual inherited
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
Remarks
Most vertex programs do not need fixed-function transform information, however GLSL shaders can refer to this state so enable this option
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLShader, Ogre::MetalProgram, and Ogre::VulkanProgram.
getPixelShader()
ID3D11PixelShader * Ogre::D3D11HLSLProgram::getPixelShader () const
getPreprocessorDefines()
const String & Ogre::D3D11HLSLProgram::getPreprocessorDefines () const inline
Sets the preprocessor defines use to compile the program.
getSize()
virtual size_t Ogre::Resource::getSize () const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getSource()
virtual const String & Ogre::GpuProgram::getSource () const inline virtual inherited
Gets the assembler source for this program.
getSourceFile()
virtual const String & Ogre::GpuProgram::getSourceFile () const inline virtual inherited
Gets the name of the file used as source for this program.
getStateCount()
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
getSubroutineSlot()
unsigned int Ogre::D3D11HLSLProgram::getSubroutineSlot (const String & subroutineSlotName) const
getSyntaxCode()
virtual const String & Ogre::GpuProgram::getSyntaxCode () const inline virtual inherited
Gets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
getTarget()
const String & Ogre::D3D11HLSLProgram::getTarget () const inline
Gets the shader target to compile down to, e.g.
'vs_1_1'.
getType()
virtual GpuProgramType Ogre::GpuProgram::getType () const inline virtual inherited
Get the program type.
getUseHlmsParser()
bool Ogre::HighLevelGpuProgram::getUseHlmsParser () const inherited
getVertexShader()
ID3D11VertexShader * Ogre::D3D11HLSLProgram::getVertexShader () const
hasCompileError()
virtual bool Ogre::GpuProgram::hasCompileError () const inline virtual inherited
Did this program encounter a compile error when loading?
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
hasDefaultParameters()
virtual bool Ogre::GpuProgram::hasDefaultParameters () const inline virtual inherited
Returns true if default parameters have been set up.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isAdjacencyInfoRequired()
virtual bool Ogre::GpuProgram::isAdjacencyInfoRequired () const inline virtual inherited
Returns whether this geometry program requires adjacency information from the input primitives.
isBackgroundLoaded()
virtual bool Ogre::Resource::isBackgroundLoaded () const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isLoaded()
virtual bool Ogre::Resource::isLoaded () const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
isLoading()
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
isManuallyLoaded()
virtual bool Ogre::Resource::isManuallyLoaded () const inline virtual inherited
Is this resource manually loaded?
isMorphAnimationIncluded()
virtual bool Ogre::GpuProgram::isMorphAnimationIncluded () const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this returns true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isPoseAnimationIncluded()
virtual bool Ogre::GpuProgram::isPoseAnimationIncluded () const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this returns true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isPrepared()
virtual bool Ogre::Resource::isPrepared () const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
isReloadable()
virtual bool Ogre::Resource::isReloadable () const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isSkeletalAnimationIncluded()
virtual bool Ogre::GpuProgram::isSkeletalAnimationIncluded () const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this returns true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isSupported()
bool Ogre::D3D11HLSLProgram::isSupported () const override virtual
Overridden from GpuProgram.
Reimplemented from Ogre::GpuProgram.
isVertexTextureFetchRequired()
virtual bool Ogre::GpuProgram::isVertexTextureFetchRequired () const inline virtual inherited
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isVpAndRtArrayIndexFromAnyShaderRequired()
virtual bool Ogre::GpuProgram::isVpAndRtArrayIndexFromAnyShaderRequired () const inline virtual inherited
Returns whether this program requires support for choosing viewport or render target index in any program or only geometry one.
load()
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
loadFromSource()
void Ogre::D3D11HLSLProgram::loadFromSource () override virtual
Internal load implementation, must be implemented by subclasses.
Implements Ogre::GpuProgram.
markForReload()
bool Ogre::Resource::markForReload () inline inherited
References Ogre::AtomicScalar< T >::cas().
prepare()
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
reinterpretGSForStreamOut()
void Ogre::D3D11HLSLProgram::reinterpretGSForStreamOut ()
reload()
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::v1::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
removeListener()
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
resetCompileError()
virtual void Ogre::GpuProgram::resetCompileError () inline virtual inherited
Reset a compile error if it occurred, allowing the load to be retried.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setAdjacencyInfoRequired()
virtual void Ogre::GpuProgram::setAdjacencyInfoRequired (bool r) inline virtual inherited
Sets whether this geometry program requires adjacency information from the input primitives.
setAutoReflectArrayBindingsInRootLayout()
virtual void Ogre::GpuProgram::setAutoReflectArrayBindingsInRootLayout (bool bReflectArrayRootLayouts) virtual inherited
Set to true to reflects the shader looking for array bindings (e.g.
uniform texture2D myTex[123]) to patch the Root Layout
Parameters
bReflectArrayRootLayouts When true (default), reflect the shader to see if the RootLayout needs patching to include array bindings
When false, we assume the RootLayout doesn't need patching and array bindings are correct. Failure to do this right may result in shader compiler errors OR everything appears fine but Vulkan Validation Layers detect it
In debug builds we will validate and reflect anyway to detect wrong usage
Reimplemented in Ogre::VulkanProgram.
setBackgroundLoaded()
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
Remarks
See also
Resource::isBackgroundLoaded . Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setBuildParametersFromReflection()
void Ogre::GpuProgram::setBuildParametersFromReflection (bool buildParams) inline inherited
setColumnMajorMatrices()
void Ogre::D3D11HLSLProgram::setColumnMajorMatrices (bool columnMajor) inline
Sets whether matrix packing in column-major order.
setComputeGroupDimensions()
virtual void Ogre::GpuProgram::setComputeGroupDimensions (Vector3 dimensions) inline virtual inherited
Sets the number of process groups dispatched by this compute program.
setEnableBackwardsCompatibility()
void Ogre::D3D11HLSLProgram::setEnableBackwardsCompatibility (bool enableBackwardsCompatibility) inline
Sets whether backwards compatibility is enabled.
setEnableIncludeHeader()
void Ogre::HighLevelGpuProgram::setEnableIncludeHeader (bool bEnable) inherited
Whether we should parse the source code looking for include files and embedding the file.
Disabled by default to avoid slowing down when #include is not used. Not needed if the API natively supports it (D3D11).
Remarks
Single line comments are supported:
// #include "MyFile.h" --> won't be included.
Block comment lines are not supported, but may not matter if the included file does not close the block:
/*
    #include "MyFile.h" --> file will be included anyway.
*/
Preprocessor macros are not supported, but should not matter:
#if SOME_MACRO
    #include "MyFile.h" --> file will be included anyway.
#endif
Recursive includes are supported (e.g. header includes a header)
Beware included files mess up error reporting (wrong lines)
Parameters
bEnable True to support #include. Must be toggled before loading the source file.
setEntryPoint()
void Ogre::D3D11HLSLProgram::setEntryPoint (const String & entryPoint) inline
Sets the entry point for this program ie the first method called.
setManuallyLoaded()
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
setManualNamedConstants()
virtual void Ogre::GpuProgram::setManualNamedConstants (const GpuNamedConstants & namedConstants) virtual inherited
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source.
See also
setManualNamedConstantsFile
setManualNamedConstantsFile()
virtual void Ogre::GpuProgram::setManualNamedConstantsFile (const String & paramDefFile) virtual inherited
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source. This method will make a low-level program search in the resource group of the program for the named file from which to load parameter names from. The file must be in the format produced by GpuNamedConstants::save.
setMorphAnimationIncluded()
virtual void Ogre::GpuProgram::setMorphAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
setNumClipDistances()
void Ogre::GpuProgram::setNumClipDistances (const uint8 numClipDistances) inherited
Sets the number of clip distances this shader uses.
Only valid for vertex shaders. Default is 0
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setPoseAnimationIncluded()
virtual void Ogre::GpuProgram::setPoseAnimationIncluded (ushort poseCount) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Parameters
poseCount The number of simultaneous poses the program can blend
setPrefabRootLayout()
void Ogre::GpuProgram::setPrefabRootLayout (const PrefabRootLayout::PrefabRootLayout & prefab) inherited
Sets a prefab root layout, mostly meant for low level materials (e.g.
postprocessing) so that users don't have to deal with Root Layouts unless they exceed defaults
Each prefab higher root layout supports more features but consumes more memory
setPreprocessorDefines()
void Ogre::D3D11HLSLProgram::setPreprocessorDefines (const String & defines) inline
Sets the preprocessor defines use to compile the program.
setReplaceVersionMacro()
virtual void Ogre::GpuProgram::setReplaceVersionMacro (bool bReplace) virtual inherited
When true:
On OpenGL: Finds the first occurrence of "ogre_glsl_ver_xxx" and only keeps "xxx" e.g. ogre_glsl_ver_330 becomes 330, ogre_glsl_ver_430 becomes 430
On Vulkan: Finds the first occurrence of "ogre_glsl_ver_xxx" and replaces it with "450"
This is disabled by default because we must scan the entire source and it's just wasted cycles when using Hlms.
However it is enabled by default on low level materials, because their source length tends to be very short and it is extremely useful/practical there
Parameters
bReplace
Reimplemented in Ogre::GLSLShader, and Ogre::VulkanProgram.
setRootLayout()
virtual void Ogre::GpuProgram::setRootLayout (GpuProgramType t, const RootLayout & rootLayout) virtual inherited
Sets a RootLayout programmatically, thus the shader source won't be parsed looking for one We will call validate()
Do not alter the type after calling this function.
This setting will be cleared if the program gets unloaded
Reimplemented in Ogre::VulkanProgram.
setSkeletalAnimationIncluded()
virtual void Ogre::GpuProgram::setSkeletalAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
setSource() [1/2]
virtual void Ogre::GpuProgram::setSource (const String & source) virtual inherited
Sets the source assembly for this program from an in-memory string.
Remarks
Setting this will have no effect until you (re)load the program.
setSource() [2/2]
virtual void Ogre::GpuProgram::setSource (const String & source, const String & debugFilename) virtual inherited
Sets the source assembly for this program from an in-memory string, while providing a path to a file, which can be needed/useful for debugging shaders (i.e.
Visual Studio Graphics Debugger)
Parameters
source Shader source code
debugFilename Optional Path to this file. Can be left blank.
setSourceFile()
virtual void Ogre::GpuProgram::setSourceFile (const String & filename) virtual inherited
Sets the filename of the source assembly for this program.
Remarks
Setting this will have no effect until you (re)load the program.
setSyntaxCode()
virtual void Ogre::GpuProgram::setSyntaxCode (const String & syntax) virtual inherited
Sets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
setTarget()
void Ogre::D3D11HLSLProgram::setTarget (const String & target)
Sets the shader target to compile down to, e.g.
'vs_1_1'.
setToLoaded()
virtual void Ogre::Resource::setToLoaded () inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
setType()
virtual void Ogre::GpuProgram::setType (GpuProgramType t) virtual inherited
Set the program type (only valid before load)
setUniformBlockBinding()
virtual void Ogre::GpuProgram::setUniformBlockBinding (const char * blockName, uint32 bindingSlot) inline virtual inherited
For GL only. Program must be bound when calling.
setUseHlmsParser()
void Ogre::HighLevelGpuProgram::setUseHlmsParser (bool bUse) inherited
Whether we should run the shader through the Hlms parser.
This parser doesn't yet have access to the entire PSO (i.e. Pixel Shader can't see Vertex Shader).
However it's still useful, specially @foreach()
Remarks
This is run after setEnableIncludeHeader
Beware included files mess up error reporting (wrong lines)
Parameters
bUse True to run source code through Hlms parser. Must be toggled before loading the source file.
setVertexTextureFetchRequired()
virtual void Ogre::GpuProgram::setVertexTextureFetchRequired (bool r) inline virtual inherited
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
setVpAndRtArrayIndexFromAnyShaderRequired()
virtual void Ogre::GpuProgram::setVpAndRtArrayIndexFromAnyShaderRequired (bool r) inline virtual inherited
Sets whether this program requires support for choosing viewport or render target index in any program or only geometry one.
touch()
virtual void Ogre::Resource::touch () virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, and Ogre::UnifiedHighLevelGpuProgram.
unload()
virtual void Ogre::Resource::unload () virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
unsetRootLayout()
virtual void Ogre::GpuProgram::unsetRootLayout () virtual inherited
Reimplemented in Ogre::VulkanProgram.
Member Data Documentation
mReinterpretingGS
bool Ogre::D3D11HLSLProgram::mReinterpretingGS
msEnableIncludeHeaderCmd
CmdEnableIncludeHeader Ogre::HighLevelGpuProgram::msEnableIncludeHeaderCmd static inherited
msUseHlmsParser
CmdUseHlmsParser Ogre::HighLevelGpuProgram::msUseHlmsParser static inherited
OGRE_AUTO_MUTEX
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreD3D11HLSLProgram.h