OGRE-Next: Ogre::ColourInterpolatorAffector Class Reference
Ogre::ColourInterpolatorAffector Class Reference
#include <OgreColourInterpolatorAffector.h>
Classes
class CmdColourAdjust
Command object for red adjust (see ParamCommand).
class CmdTimeAdjust
Command object for red adjust (see ParamCommand).
Public Types
enum { MAX_STAGES = 6 }
Public Member Functions
ColourInterpolatorAffector (ParticleSystem *psys)
Default constructor.
void _affectParticles (ParticleSystem *pSystem, Real timeElapsed) override
See ParticleAffector.
void _initParticle (Ogre::Particle *pParticle) override
See ParticleAffector.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
ColourValue getColourAdjust (size_t index) const
ParamDictionary * getParamDictionary ()
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary () const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters () const
Retrieves a list of parameters valid for this object.
Real getTimeAdjust (size_t index) const
const String & getType () const
Returns the name of the type of affector.
void setColourAdjust (size_t index, ColourValue colour)
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setTimeAdjust (size_t index, Real time)
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Static Public Attributes
static CmdColourAdjust msColourCmd [MAX_STAGES]
static CmdTimeAdjust msTimeCmd [MAX_STAGES]
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_STAGES
Constructor & Destructor Documentation
ColourInterpolatorAffector()
Ogre::ColourInterpolatorAffector::ColourInterpolatorAffector (ParticleSystem * psys)
Default constructor.
Member Function Documentation
_affectParticles()
void Ogre::ColourInterpolatorAffector::_affectParticles (ParticleSystem * pSystem, Real timeElapsed) override virtual
See ParticleAffector.
Implements Ogre::ParticleAffector.
_initParticle()
void Ogre::ColourInterpolatorAffector::_initParticle (Ogre::Particle * pParticle) override virtual
See ParticleAffector.
Reimplemented from Ogre::ParticleAffector.
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
getColourAdjust()
ColourValue Ogre::ColourInterpolatorAffector::getColourAdjust (size_t index) const
getParamDictionary() [1/2]
ParamDictionary * Ogre::StringInterface::getParamDictionary () inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary * Ogre::StringInterface::getParamDictionary () const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList & Ogre::StringInterface::getParameters () const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getTimeAdjust()
Real Ogre::ColourInterpolatorAffector::getTimeAdjust (size_t index) const
getType()
const String & Ogre::ParticleAffector::getType () const inline inherited
Returns the name of the type of affector.
Remarks
This property is useful for determining the type of affector procedurally so another can be created.
setColourAdjust()
void Ogre::ColourInterpolatorAffector::setColourAdjust (size_t index, ColourValue colour)
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setTimeAdjust()
void Ogre::ColourInterpolatorAffector::setTimeAdjust (size_t index, Real time)
Member Data Documentation
msColourCmd
CmdColourAdjust Ogre::ColourInterpolatorAffector::msColourCmd[MAX_STAGES] static
msTimeCmd
CmdTimeAdjust Ogre::ColourInterpolatorAffector::msTimeCmd[MAX_STAGES] static
The documentation for this class was generated from the following file:
OgreColourInterpolatorAffector.h