OGRE-Next: Ogre::MovablePlane Class Reference
Ogre::MovablePlane Class Reference
Component | Core » Scene
Definition of a Plane that may be attached to a node, and the derived details of it retrieved simply.
#include <OgreMovablePlane.h>
Public Types
typedef FastArray< MovableObject * > MovableObjectArray
enum Side { NO_SIDE , POSITIVE_SIDE , NEGATIVE_SIDE , BOTH_SIDE }
The "positive side" of the plane is the half space to which the plane normal points.
Public Member Functions
MovablePlane (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager)
MovablePlane (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager, const Plane &rhs)
MovablePlane (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager, const Vector3 &rkNormal, const Vector3 &rkPoint)
MovablePlane (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager, const Vector3 &rkNormal, Real fConstant)
Construct a plane through a normal, and a distance to move the plane along the normal.
MovablePlane (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager, const Vector3 &rkPoint0, const Vector3 &rkPoint1, const Vector3 &rkPoint2)
~MovablePlane () override
const Plane & _getDerivedPlane () const
Get the derived plane as transformed by its parent node.
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager () const
Get the manager of this object, if any (internal use only)
ObjectData & _getObjectData ()
Returns a direct access to the ObjectData state.
const Matrix4 & _getParentNodeFullTransform () const
Returns the full transformation of the parent sceneNode or the attachingPoint node.
virtual void _notifyAttached (Node *parent)
Internal method called to notify the object that it has been attached to a node.
void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyParentNodeMemoryChanged ()
virtual void _notifyStaticDirty () const
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
virtual void _releaseManualHardwareResources ()
Notifies the movable object that hardware resources were lost.
virtual void _restoreManualHardwareResources ()
Notifies the movable object that hardware resources should be restored.
void _updateRenderQueue (RenderQueue *, Camera *, const Camera *) override
Overridden from MovableObject.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
void detachFromParent ()
Detaches an object from a parent SceneNode if attached.
const StringVector & getAnimableValueNames () const
Gets a list of animable value names for this object.
const AxisAlignedBox & getBoundingBox () const
Overridden from MovableObject.
RealAsUint getCachedDistanceToCamera () const
Returns the distance to camera as calculated in cullFrustum()
Real getCachedDistanceToCameraAsReal () const
Returns the distance to camera as calculated in cullFrustum()
bool getCastShadows () const
Returns whether shadow casting is enabled for this object.
unsigned char getCurrentMeshLod () const
Real getDistance (const Vector3 &rkPoint) const
This is a pseudodistance.
IdType getId () const
Get the unique id of this object.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
Listener * getListener () const
Gets the current listener for this object.
Aabb getLocalAabb () const
Retrieves the local axis-aligned bounding box for this object.
float getLocalRadius () const
See getLocalAabb and getWorldRadius.
const String & getMovableType () const override
Overridden from MovableObject.
const String & getName () const
Returns the name of this object.
Node * getParentNode () const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode () const
uint32 getQueryFlags () const
Returns the query flags relevant for this object.
Real getRenderingDistance () const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
uint8 getRenderQueueGroup () const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
Real getShadowRenderingDistance () const
Gets the distance at which batches are no longer casting shadows.
Side getSide (const AxisAlignedBox &rkBox) const
Returns the side where the alignedBox is.
Side getSide (const Vector3 &centre, const Vector3 &halfSize) const
Returns which side of the plane that the given box lies on.
Side getSide (const Vector3 &rkPoint) const
SkeletonInstance * getSkeletonInstance () const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
uint32 getVisibilityFlags () const
Returns the visibility flags relevant for this object.
bool getVisible () const
Gets this object whether to be visible or not, if it has a renderable component.
Aabb getWorldAabb () const
Gets the axis aligned box in world space.
Aabb getWorldAabbUpdated ()
Gets the axis aligned box in world space.
float getWorldRadius () const
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
float getWorldRadiusUpdated ()
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
virtual void instanceBatchCullFrustumThreaded (const Frustum *frustum, const Camera *lodCamera, uint32 combinedVisibilityFlags)
bool isAttached () const
Returns true if this object is attached to a Node.
bool isStatic () const
Checks whether this MovableObject is static.
bool isVisible () const
Returns whether or not this object is supposed to be visible or not.
Real normalise ()
Normalises the plane.
bool operator!= (const Plane &rhs) const
bool operator() (const IdObject &left, const IdObject &right)
bool operator() (const IdObject *left, const IdObject *right)
Plane operator- () const
Get flipped plane, with same location but reverted orientation.
bool operator== (const Plane &rhs) const
Comparison operator.
Vector3 projectVector (const Vector3 &v) const
Project a vector onto the plane.
const LightList & queryLights () const
Gets a list of lights, ordered relative to how close they are to this movable object.
void redefine (const Vector3 &p0, const Vector3 &p1, const Vector3 &p2)
Redefine this plane based on 3 points.
void redefine (const Vector3 &rkNormal, const Vector3 &rkPoint)
Redefine this plane based on a normal and a point.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
void setLocalAabb (const Aabb box)
Sets the local axis-aligned bounding box for this object.
void setName (const String &name)
Sets a custom name for this node.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
void setShadowRenderingDistance (Real dist)
Sets the distance at which the object is no longer casting shadows.
bool setStatic (bool bStatic)
Turns this Node into static or dynamic.
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
Static Public Member Functions
static void buildLightList (const size_t numNodes, ObjectData t, const LightListInfo &globalLightList)
static void calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox *outBox)
static void cullFrustum (const size_t numNodes, ObjectData t, const Camera *frustum, uint32 sceneVisibilityFlags, MovableObjectArray &outCulledObjects, const Camera *lodCamera)
static void cullLights (const size_t numNodes, ObjectData t, uint32 sceneLightMask, LightListInfo &outGlobalLightList, const FrustumVec &frustums, const FrustumVec &cubemapFrustums)
See SceneManager::cullLights & see MovableObject::cullFrustum.
static uint32 getDefaultLightMask ()
Get the default light mask for all future MovableObject instances.
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultLightMask (uint32 mask)
Set the default light mask for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
static void updateAllBounds (const size_t numNodes, ObjectData t)
Public Attributes
Real d
size_t mGlobalIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
size_t mParentIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
RenderableArray mRenderables
Vector3 normal
Static Public Attributes
static const FastArray< Real > c_DefaultLodMesh
Detailed Description
Definition of a Plane that may be attached to a node, and the derived details of it retrieved simply.
Remarks
This plane is not here for rendering purposes, it's to allow you to attach planes to the scene in order to have them move and follow nodes on their own, which is useful if you're using the plane for some kind of calculation, e.g. reflection.
Member Typedef Documentation
MovableObjectArray
typedef FastArray<MovableObject *> Ogre::MovableObject::MovableObjectArray inherited
See also
SceneManager::cullFrustum
Remarks
We don't pass by reference on purpose (avoid implicit aliasing) We perform frustum culling AND test visibility mask at the same time
Parameters
frustum Frustum to clip against
sceneVisibilityFlags Combined scene's visibility flags (i.e. viewport | scene). Set LAYER_SHADOW_CASTER bit if you want to exclude non-shadow casters.
outCulledObjects Out. List of objects that are (fully or partially) inside the frustum and should be rendered
lodCamera Camera in which lod levels calculations are based (i.e. during shadow pass renders) Note however, we only use this camera to calulate if should be visible according to mUpperDistance
Member Enumeration Documentation
Side
enum Ogre::Plane::Side inherited
The "positive side" of the plane is the half space to which the plane normal points.
The "negative side" is the other half space. The flag "no side" indicates the plane itself.
Enumerator
NO_SIDE
POSITIVE_SIDE
NEGATIVE_SIDE
BOTH_SIDE
Constructor & Destructor Documentation
MovablePlane() [1/5]
Ogre::MovablePlane::MovablePlane (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager)
MovablePlane() [2/5]
Ogre::MovablePlane::MovablePlane (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager, const Plane & rhs)
MovablePlane() [3/5]
Ogre::MovablePlane::MovablePlane (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager, const Vector3 & rkNormal, Real fConstant)
Construct a plane through a normal, and a distance to move the plane along the normal.
MovablePlane() [4/5]
Ogre::MovablePlane::MovablePlane (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager, const Vector3 & rkNormal, const Vector3 & rkPoint)
MovablePlane() [5/5]
Ogre::MovablePlane::MovablePlane (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager, const Vector3 & rkPoint0, const Vector3 & rkPoint1, const Vector3 & rkPoint2)
~MovablePlane()
Ogre::MovablePlane::~MovablePlane () inline override
Member Function Documentation
_getDerivedPlane()
const Plane & Ogre::MovablePlane::_getDerivedPlane () const
Get the derived plane as transformed by its parent node.
_getLightList()
LightList * Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
_getManager()
SceneManager * Ogre::MovableObject::_getManager () const inline inherited
Get the manager of this object, if any (internal use only)
_getObjectData()
ObjectData & Ogre::MovableObject::_getObjectData () inline inherited
Returns a direct access to the ObjectData state.
_getParentNodeFullTransform()
const Matrix4 & Ogre::MovableObject::_getParentNodeFullTransform () const inherited
Returns the full transformation of the parent sceneNode or the attachingPoint node.
_notifyAttached()
virtual void Ogre::MovableObject::_notifyAttached (Node * parent) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::v1::Entity, and Ogre::ParticleSystem.
_notifyManager()
void Ogre::MovableObject::_notifyManager (SceneManager * man) inline inherited
Notify the object of it's manager (internal use only)
_notifyParentNodeMemoryChanged()
virtual void Ogre::MovableObject::_notifyParentNodeMemoryChanged () inline virtual inherited
See also
Node::_callMemoryChangeListeners
Reimplemented in Ogre::Item.
_notifyStaticDirty()
virtual void Ogre::MovableObject::_notifyStaticDirty () const inline virtual inherited
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
See also
SceneManager::notifyStaticDirty
_releaseManualHardwareResources()
virtual void Ogre::MovableObject::_releaseManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources were lost.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::v1::BillboardSet, Ogre::v1::ManualObject, Ogre::ManualObject, and Ogre::v1::Rectangle2D.
_restoreManualHardwareResources()
virtual void Ogre::MovableObject::_restoreManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources should be restored.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::v1::Rectangle2D.
_updateRenderQueue()
void Ogre::MovablePlane::_updateRenderQueue (RenderQueue * , Camera * , const Camera *) inline override virtual
Overridden from MovableObject.
Reimplemented from Ogre::MovableObject.
addQueryFlags()
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
addVisibilityFlags()
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
buildLightList()
static void Ogre::MovableObject::buildLightList (const size_t numNodes, ObjectData t, const LightListInfo & globalLightList) static inherited
See also
SceneManager::buildLightList
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
Parameters
globalLightList List of lights already culled against all possible frustums and reorganized contiguously for SoA
calculateCastersBox()
static void Ogre::MovableObject::calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox * outBox) static inherited
createAnimableValue()
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References OGRE_EXCEPT.
cullFrustum()
static void Ogre::MovableObject::cullFrustum (const size_t numNodes, ObjectData t, const Camera * frustum, uint32 sceneVisibilityFlags, MovableObjectArray & outCulledObjects, const Camera * lodCamera) static inherited
cullLights()
static void Ogre::MovableObject::cullLights (const size_t numNodes, ObjectData t, uint32 sceneLightMask, LightListInfo & outGlobalLightList, const FrustumVec & frustums, const FrustumVec & cubemapFrustums) static inherited
See SceneManager::cullLights & see MovableObject::cullFrustum.
Produces the global list of visible lights that is needed in buildLightList
Remarks
We don't pass ObjectData by reference on purpose (avoid implicit aliasing) It's declared here because all affected elements are from MovableObject IMPORTANT: It is assumed that all objects in ObjectData are Lights.
Parameters
outGlobalLightList Output, a list of lights, contiguously placed
frustums An array of all frustums we need to check against
cubemapFrustums An array of all frustums that are used at least once as cubemaps
See also
SceneManager::createCamera
detachFromParent()
void Ogre::MovableObject::detachFromParent () inherited
Detaches an object from a parent SceneNode if attached.
getAnimableValueNames()
const StringVector & Ogre::AnimableObject::getAnimableValueNames () const inline inherited
Gets a list of animable value names for this object.
References OGRE_EXCEPT.
getBoundingBox()
const AxisAlignedBox & Ogre::MovablePlane::getBoundingBox () const inline
Overridden from MovableObject.
getCachedDistanceToCamera()
RealAsUint Ogre::MovableObject::getCachedDistanceToCamera () const inline inherited
Returns the distance to camera as calculated in cullFrustum()
getCachedDistanceToCameraAsReal()
Real Ogre::MovableObject::getCachedDistanceToCameraAsReal () const inline inherited
Returns the distance to camera as calculated in cullFrustum()
getCastShadows()
bool Ogre::MovableObject::getCastShadows () const inline inherited
Returns whether shadow casting is enabled for this object.
getCurrentMeshLod()
unsigned char Ogre::MovableObject::getCurrentMeshLod () const inline inherited
getDefaultLightMask()
static uint32 Ogre::MovableObject::getDefaultLightMask () inline static inherited
Get the default light mask for all future MovableObject instances.
getDefaultQueryFlags()
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
getDefaultVisibilityFlags()
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
getDistance()
Real Ogre::Plane::getDistance (const Vector3 & rkPoint) const inline inherited
This is a pseudodistance.
The sign of the return value is positive if the point is on the positive side of the plane, negative if the point is on the negative side, and zero if the point is on the plane.
The absolute value of the return value is the true distance only when the plane normal is a unit length vector.
References Ogre::Vector3::dotProduct().
Referenced by Ogre::PlaneBoundedVolume::intersects().
getId()
IdType Ogre::IdObject::getId () const inline inherited
Get the unique id of this object.
getLightMask()
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
getListener()
Listener * Ogre::MovableObject::getListener () const inline inherited
Gets the current listener for this object.
getLocalAabb()
Aabb Ogre::MovableObject::getLocalAabb () const inherited
Retrieves the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
getLocalRadius()
float Ogre::MovableObject::getLocalRadius () const inherited
See getLocalAabb and getWorldRadius.
getMovableType()
const String & Ogre::MovablePlane::getMovableType () const override virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
getName()
const String & Ogre::MovableObject::getName () const inline inherited
Returns the name of this object.
getParentNode()
Node * Ogre::MovableObject::getParentNode () const inline inherited
Returns the node to which this object is attached.
getParentSceneNode()
SceneNode * Ogre::MovableObject::getParentSceneNode () const inline inherited
getQueryFlags()
uint32 Ogre::MovableObject::getQueryFlags () const inline inherited
Returns the query flags relevant for this object.
getRenderingDistance()
Real Ogre::MovableObject::getRenderingDistance () const inline inherited
Gets the distance at which batches are no longer rendered.
getRenderingMinPixelSize()
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
getRenderQueueGroup()
uint8 Ogre::MovableObject::getRenderQueueGroup () const inline inherited
Gets the queue group for this entity, see setRenderQueueGroup for full details.
getShadowRenderingDistance()
Real Ogre::MovableObject::getShadowRenderingDistance () const inline inherited
Gets the distance at which batches are no longer casting shadows.
getSide() [1/3]
Side Ogre::Plane::getSide (const AxisAlignedBox & rkBox) const inherited
Returns the side where the alignedBox is.
The flag BOTH_SIDE indicates an intersecting box. One corner ON the plane is sufficient to consider the box and the plane intersecting.
getSide() [2/3]
Side Ogre::Plane::getSide (const Vector3 & centre, const Vector3 & halfSize) const inherited
Returns which side of the plane that the given box lies on.
The box is defined as centre/half-size pairs for effectively.
Parameters
centre The centre of the box.
halfSize The half-size of the box.
Returns
POSITIVE_SIDE if the box complete lies on the "positive side" of the plane, NEGATIVE_SIDE if the box complete lies on the "negative side" of the plane, and BOTH_SIDE if the box intersects the plane.
getSide() [3/3]
Side Ogre::Plane::getSide (const Vector3 & rkPoint) const inline inherited
Referenced by Ogre::PlaneBoundedVolume::intersects().
getSkeletonInstance()
SkeletonInstance * Ogre::MovableObject::getSkeletonInstance () const inline inherited
getUserObjectBindings() [1/2]
UserObjectBindings & Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/2]
const UserObjectBindings & Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getVisibilityFlags()
uint32 Ogre::MovableObject::getVisibilityFlags () const inline inherited
Returns the visibility flags relevant for this object.
Reserved visibility flags are not returned.
getVisible()
bool Ogre::MovableObject::getVisible () const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
getWorldAabb()
Aabb Ogre::MovableObject::getWorldAabb () const inherited
Gets the axis aligned box in world space.
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. See getWorldAabbUpdated() if you need the update process to be guaranteed
getWorldAabbUpdated()
Aabb Ogre::MovableObject::getWorldAabbUpdated () inherited
Gets the axis aligned box in world space.
Remarks
Unlike getWorldAabb, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
getWorldRadius()
float Ogre::MovableObject::getWorldRadius () const inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. See getWorldRadiusUpdated() if you need the update process to be guaranteed
getWorldRadiusUpdated()
float Ogre::MovableObject::getWorldRadiusUpdated () inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Unlike getWorldRadius, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
instanceBatchCullFrustumThreaded()
virtual void Ogre::MovableObject::instanceBatchCullFrustumThreaded (const Frustum * frustum, const Camera * lodCamera, uint32 combinedVisibilityFlags) inline virtual inherited
See also
InstancingTheadedCullingMethod,
InstanceBatch::instanceBatchCullFrustumThreaded
isAttached()
bool Ogre::MovableObject::isAttached () const inline inherited
Returns true if this object is attached to a Node.
isStatic()
bool Ogre::MovableObject::isStatic () const inherited
Checks whether this MovableObject is static.
See also
setStatic
isVisible()
bool Ogre::MovableObject::isVisible () const inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account visibility flags and the setVisible, but not rendering distance.
normalise()
Real Ogre::Plane::normalise () inherited
Normalises the plane.
Remarks
This method normalises the plane's normal and the length scale of d is as well.
Note
This function will not crash for zero-sized vectors, but there will be no changes made to their components.
Returns
The previous length of the plane's normal.
operator!=()
bool Ogre::Plane::operator!= (const Plane & rhs) const inline inherited
References Ogre::Plane::d, and Ogre::Plane::normal.
operator()() [1/2]
bool Ogre::IdObject::operator() (const IdObject & left, const IdObject & right) inline inherited
operator()() [2/2]
bool Ogre::IdObject::operator() (const IdObject * left, const IdObject * right) inline inherited
operator-()
Plane Ogre::Plane::operator- () const inline inherited
Get flipped plane, with same location but reverted orientation.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
operator==()
bool Ogre::Plane::operator== (const Plane & rhs) const inline inherited
Comparison operator.
References Ogre::Plane::d, and Ogre::Plane::normal.
projectVector()
Vector3 Ogre::Plane::projectVector (const Vector3 & v) const inherited
Project a vector onto the plane.
Remarks
This gives you the element of the input vector that is perpendicular to the normal of the plane. You can get the element which is parallel to the normal of the plane by subtracting the result of this method from the original vector, since parallel + perpendicular = original.
Parameters
v The input vector
queryLights()
const LightList & Ogre::MovableObject::queryLights () const inline inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
The lights are filled in
See also
buildLightList
Returns
The list of lights use to lighting this object.
redefine() [1/2]
void Ogre::Plane::redefine (const Vector3 & p0, const Vector3 & p1, const Vector3 & p2) inline inherited
Redefine this plane based on 3 points.
References Ogre::Vector3::dotProduct(), and Ogre::Vector3::normalisedCopy().
redefine() [2/2]
void Ogre::Plane::redefine (const Vector3 & rkNormal, const Vector3 & rkPoint) inline inherited
Redefine this plane based on a normal and a point.
References Ogre::Vector3::dotProduct().
removeQueryFlags()
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
removeVisibilityFlags()
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
setCastShadows()
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
setDefaultLightMask()
static void Ogre::MovableObject::setDefaultLightMask (uint32 mask) inline static inherited
Set the default light mask for all future MovableObject instances.
setDefaultQueryFlags()
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
setDefaultVisibilityFlags()
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
setLightMask()
void Ogre::MovableObject::setLightMask (uint32 lightMask) inline inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
setListener()
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
setLocalAabb()
void Ogre::MovableObject::setLocalAabb (const Aabb box) inherited
Sets the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
setName()
void Ogre::MovableObject::setName (const String & name) inline inherited
Sets a custom name for this node.
Doesn't have to be unique
setQueryFlags()
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
setRenderingDistance()
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Parameters
dist Distance beyond which the object will not be rendered (the default is FLT_MAX, which means objects are always rendered). Values equal or below zero will be ignored, and cause an assertion in debug mode.
setRenderingMinPixelSize()
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
setRenderQueueGroup()
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Valid render queue ids are between 0 & 254 inclusive
Reimplemented in Ogre::Decal, Ogre::v1::Entity, Ogre::InternalCubemapProbe, Ogre::Light, and Ogre::ParticleSystem.
setShadowRenderingDistance()
void Ogre::MovableObject::setShadowRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer casting shadows.
Parameters
dist Distance beyond which the object will not cast shadows (the default is FLT_MAX, which means objects are always casting shadows). Values equal or below zero will be ignored, and cause an assertion in debug mode.
Note
ShadowRenderingDistance will be clamped to RenderingDistance value
See also
setRenderingDistance
setStatic()
bool Ogre::MovableObject::setStatic (bool bStatic) inherited
Turns this Node into static or dynamic.
Remarks
Switching between dynamic and static has some overhead and forces to update all static scene when converted to static. So don't do it frequently. Static objects are not updated every frame, only when requested explicitly. Use this feature if you plan to have this object unaltered for a very long times
Note all MovableObjects support switching between static & dynamic after they have been created (eg. InstancedEntity)
Changing this attribute will cause to switch the attribute to our parent node, and as a result, all of its other attached entities.
See also
Node::setStatic
Returns
True if setStatic made an actual change. False otherwise. Can fail because the object was already static/dynamic, or because switching is not supported
setVisibilityFlags()
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags that is applied a binary 'and' with the SceneManager's mask and a compositor node pass. To exclude particular objects from rendering. Changes to reserved visibility flags are ignored (won't take effect).
setVisible()
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
updateAllBounds()
static void Ogre::MovableObject::updateAllBounds (const size_t numNodes, ObjectData t) static inherited
See also
SceneManager::updateAllBounds
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
Member Data Documentation
c_DefaultLodMesh
const FastArray<Real> Ogre::MovableObject::c_DefaultLodMesh static inherited
d
Real Ogre::Plane::d inherited
Referenced by Ogre::Plane::operator!=(), Ogre::Matrix4::operator*(), and Ogre::Plane::operator==().
mGlobalIndex
size_t Ogre::MovableObject::mGlobalIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
mParentIndex
size_t Ogre::MovableObject::mParentIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
mRenderables
RenderableArray Ogre::MovableObject::mRenderables inherited
normal
Vector3 Ogre::Plane::normal inherited
Referenced by Ogre::Plane::operator!=(), Ogre::Matrix4::operator*(), and Ogre::Plane::operator==().
The documentation for this class was generated from the following file:
OgreMovablePlane.h