OGRE-Next: Ogre::LinearResampler Struct Reference
Ogre::LinearResampler Struct Reference
Core » Image
#include <OgreImageResampler.h>
Static Public Member Functions
static void scale (const TextureBox &src, PixelFormatGpu srcFormat, const TextureBox &dst, PixelFormatGpu dstFormat)
Member Function Documentation
scale()
static void Ogre::LinearResampler::scale (const TextureBox & src, PixelFormatGpu srcFormat, const TextureBox & dst, PixelFormatGpu dstFormat) inline static
References Ogre::TextureBox::atFromOffsettedOrigin(), Ogre::TextureBox::bytesPerImage, Ogre::TextureBox::bytesPerRow, Ogre::TextureBox::depth, Ogre::PixelFormatGpuUtils::getBytesPerPixel(), Ogre::TextureBox::getDepthOrSlices(), Ogre::TextureBox::height, Ogre::PixelFormatGpuUtils::packColour(), UNPACK, and Ogre::TextureBox::width.
Referenced by Ogre::LinearResampler_Byte< channels >::scale().
The documentation for this struct was generated from the following file:
OgreImageResampler.h