
// This file has been auto-generated by clone_particle_systems.py
// Please DO NOT manually edit this file. Any subsequent invocation of
// clone_particle_systems.py will overwrite your modifications.
#include "OgreParticleSystem.h"
using namespace Ogre;
//-----------------------------------------------------------------------------
void ParticleSystem::_cloneFrom( const ParticleSystem *_original )
{
    OGRE_ASSERT_HIGH( dynamic_cast<const ParticleSystem *>( _original ) );

    const ParticleSystem *original = static_cast<const ParticleSystem *>( _original );
    this->mBoundsAutoUpdate = original->mBoundsAutoUpdate;
    this->mBoundsUpdateTime = original->mBoundsUpdateTime;
    this->mUpdateRemainTime = original->mUpdateRemainTime;
    this->mIsRendererConfigured = original->mIsRendererConfigured;
    this->mDefaultWidth = original->mDefaultWidth;
    this->mDefaultHeight = original->mDefaultHeight;
    this->mSpeedFactor = original->mSpeedFactor;
    this->mIterationInterval = original->mIterationInterval;
    this->mIterationIntervalSet = original->mIterationIntervalSet;
    this->mSorted = original->mSorted;
    this->mLocalSpace = original->mLocalSpace;
    this->mNonvisibleTimeout = original->mNonvisibleTimeout;
    this->mNonvisibleTimeoutSet = original->mNonvisibleTimeoutSet;
    this->mTimeSinceLastVisible = original->mTimeSinceLastVisible;
    this->mLastVisibleFrame = original->mLastVisibleFrame;
    this->mTimeController = original->mTimeController;
    this->mEmittedEmitterPoolInitialised = original->mEmittedEmitterPoolInitialised;
    this->mIsEmitting = original->mIsEmitting;
    this->mParticleEmitterRootNode = original->mParticleEmitterRootNode;
    this->mTranslateParticleDirectionIntoWorldSpace =
        original->mTranslateParticleDirectionIntoWorldSpace;
    this->mRenderer = original->mRenderer;
    this->mCullIndividual = original->mCullIndividual;
    this->mPoolSize = original->mPoolSize;
    this->mEmittedEmitterPoolSize = original->mEmittedEmitterPoolSize;
    this->mResourceGroupName = original->mResourceGroupName;
    this->mMaterialName = original->mMaterialName;
    this->mMaterial = original->mMaterial;
    this->mActiveParticles = original->mActiveParticles;
    this->mFreeParticles = original->mFreeParticles;
    this->mParticlePool = original->mParticlePool;
    this->mEmittedEmitterPool = original->mEmittedEmitterPool;
    this->mFreeEmittedEmitters = original->mFreeEmittedEmitters;
    this->mActiveEmittedEmitters = original->mActiveEmittedEmitters;
    this->mEmitters = original->mEmitters;
    this->mAffectors = original->mAffectors;
    this->mRendererType = original->mRendererType;
    this->mOrigin = original->mOrigin;
}
