
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class CategoryGrouping final : public CategoryGroupingBase
{
    MainWindow *m_mainWindow;

    Ogre::String              m_currGroup;
    std::vector<Ogre::String> m_grouplessEntries;
    std::vector<Ogre::String> m_groupEntries;

    bool m_editing;

protected:
    void OnGroupChoice( wxCommandEvent &event ) override;
    void OnButtonClick( wxCommandEvent &event ) override;
    void OnListBoxDClick( wxCommandEvent &event ) override;
    void OnSearchText( wxCommandEvent &event ) override;

    void addSelectedToGroup();
    void removeSelectedFromGroup();

    void refreshGroupless();
    void refreshGrouped();

public:
    CategoryGrouping( MainWindow *parent );
};

OGRE_ASSUME_NONNULL_END
