
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class DatablockList final : public DatablockListBase
{
    MainWindow *m_mainWindow;

    bool m_editing;

protected:
    // Handlers for DatablockListBase events.
    void OnDatablockSelect( wxCommandEvent &event ) override;
    void OnCheckbox( wxCommandEvent &event ) override;
    void OnSearchText( wxCommandEvent &event ) override;

public:
    DatablockList( MainWindow *parent );

    void populateFromDatabase( bool bReasonActiveMeshChanged = false );
};

OGRE_ASSUME_NONNULL_END
