
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class DatablockList final : public DatablockListBase
{
    MainWindow *m_mainWindow;

    bool m_editing;

    /// If this is true, then the datablock is on the list because it's the active one.
    /// If it weren't the active one, it would be filtered out.
    bool m_activeWouldBeFiltered;

protected:
    // Handlers for DatablockListBase events.
    void OnDatablockSelect( wxCommandEvent &event ) override;
    void OnCheckbox( wxCommandEvent &event ) override;
    void OnSearchText( wxCommandEvent &event ) override;

public:
    DatablockList( MainWindow *parent );

    void populateFromDatabase( bool bReasonActiveMeshChanged = false );

    void notifyDatablockSelectChanged();
};

OGRE_ASSUME_NONNULL_END
