
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class DatablockList : public DatablockListBase
{
    MainWindow *m_mainWindow;

    bool m_editing;

protected:
    void populateFromDatabase();

    // Handlers for DatablockListBase events.
    void OnDatablockSelect( wxCommandEvent &event );
    void OnCheckbox( wxCommandEvent &event );
    void OnSearchText( wxCommandEvent &event );

public:
    DatablockList( MainWindow *parent );
};

OGRE_ASSUME_NONNULL_END
