
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class LightPanel final : public LightPanelBase
{
    MainWindow *m_mainWindow;

    Ogre::SceneNode              *m_masterNode;
    Ogre::SceneNode *ogre_nonnull m_lightNodes[3];

    bool m_editing;

protected:
    // Handlers for LightPanelBase events.
    void OnPresetChoice( wxCommandEvent &event ) override;
    void OnCheckbox( wxCommandEvent &event ) override;
    void OnEulerText( wxCommandEvent &event ) override;
    void OnSlider( wxCommandEvent &event ) override;
    void OnText( wxCommandEvent &event ) override;

public:
    LightPanel( MainWindow *parent );

    void setCoordinateConvention( CoordinateConvention::CoordinateConvention newConvention );
    void setCameraRelative( const bool bCameraRelative );
    void notifyMeshChanged();

    void setPreset( const uint32_t preset );
};

OGRE_ASSUME_NONNULL_END
