
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

class MainWindow;

OGRE_ASSUME_NONNULL_BEGIN

class MeshList final : public MeshListBase
{
    struct MeshEntry
    {
        Ogre::String name;
        Ogre::String resourceGroup;
    };

    MainWindow *m_mainWindow;

    std::vector<MeshEntry> m_meshes;

    bool m_editing;

protected:
    void populateFromDatabase();

    // Handlers for MeshListBase events.
    void OnMeshSelect( wxCommandEvent &event ) override;
    void OnSearchText( wxCommandEvent &event ) override;

public:
    MeshList( MainWindow *parent );
};

OGRE_ASSUME_NONNULL_END
