
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "OgrePrerequisites.h"

OGRE_ASSUME_NONNULL_BEGIN

namespace ColourSection
{
    enum ColourSection
    {
        Diffuse,
        Specular,
        Fresnel,
        NumColourSection
    };
}

class PbsParametersPanel : public PbsParametersPanelBase
{
    /// Synchronizes all colour widgets so that when one changes, the others are changed immediately.
    struct ColourWidgets
    {
        wxTextCtrl *ogre_nonnull rgbaText[4];
        wxTextCtrl              *rgbaHtml;
        wxButton                *buttonPicker;

        /// Synchronizes all widgets based on what's in rgbaText[i].
        void fromRgbaText();
        /// Synchronizes all widgets based on what's in buttonPicker (actually, what's provided in rgba).
        void fromButton( const uint32_t rgba );
        /// Synchronizes all widgets based on what's in rgbaHtml.
        void fromHtml();
    };

    struct EditingScope
    {
        bool &editing;

        EditingScope( bool &bValue ) : editing( bValue ) { editing = true; }
        ~EditingScope() { editing = false; }
    };

    bool m_editing;

    /// Creates all linked widgets that form part of one ColourWidgets based on the requested section.
    ColourWidgets getColourWidgets( ColourSection::ColourSection section );

protected:
    // Handlers for PbsParametersPanelBase events.
    void OnColourHtml( wxCommandEvent &event ) override;
    void OnColourButton( wxCommandEvent &event ) override;
    void OnColourText( wxCommandEvent &event ) override;
    void OnCheckBox( wxCommandEvent &event ) override;
    void OnSlider( wxCommandEvent &event ) override;
    void OnSliderText( wxCommandEvent &event ) override;
    void OnTransparencyMode( wxCommandEvent &event ) override;
    void OnCheckbox( wxCommandEvent &event ) override;

public:
    PbsParametersPanel( wxWindow *parent );
};

OGRE_ASSUME_NONNULL_END
