
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

OGRE_ASSUME_NONNULL_BEGIN

class MainWindow;

namespace ColourSection
{
    enum ColourSection
    {
        Diffuse,
        Specular,
        Fresnel,
        NumColourSection
    };
}

namespace PbsSliders
{
    enum PbsSliders
    {
        Fresnel,
        Roughness,
        Transparency,
        NumPbsSliders
    };
}

class PbsParametersPanel final : public PbsParametersPanelBase
{
    /// Synchronizes all colour widgets so that when one changes, the others are changed immediately.
    struct ColourWidgets
    {
        wxTextCtrl *ogre_nonnull rgbaText[3];
        wxTextCtrl              *rgbaHtml;
        wxButton                *buttonPicker;

        /// Synchronizes all widgets based on what's in rgbaText[i].
        void fromRgbaText();
        /// Synchronizes all widgets based on what's in buttonPicker (actually, what's provided in rgba).
        void fromButton( const uint32_t rgba );
        /// Synchronizes all widgets based on what's in rgbaHtml.
        void fromHtml();
    };

    MainWindow *m_mainWindow;

    enum DirtyState : uint8_t
    {
        DirtyStateUpToDate,
        DirtyStateDirty,
        DirtyStateDirtyFromSlider,
    };

    bool       m_editing;
    DirtyState m_datablockDirty;
    bool       m_ignoreUndo;
    /// wxWidgets emits UndoMouseUp() then OnSlider(). Thus if we set m_ignoreUndo = false in UndoMouseUp
    /// we'll push the current datablock.
    /// This doesn't happen with keyboard because it emits OnSlider() then UndoKeyUp().
    bool m_undoMouseUp;

    /// Creates all linked widgets that form part of one ColourWidgets based on the requested section.
    ColourWidgets getColourWidgets( ColourSection::ColourSection section );

    SliderTextWidget getSliderWidgets( PbsSliders::PbsSliders slider );

    void syncFresnelCheckbox();

protected:
    // Handlers for PbsParametersPanelBase events.
    void OnColourHtml( wxCommandEvent &event ) override;
    void OnColourButton( wxCommandEvent &event ) override;
    void OnColourText( wxCommandEvent &event ) override;
    void OnCheckbox( wxCommandEvent &event ) override;
    void OnSlider( wxCommandEvent &event ) override;
    void OnSliderText( wxCommandEvent &event ) override;
    void OnWorkflowChange( wxCommandEvent &event ) override;
    void OnSettingDirty( wxCommandEvent &event ) override;
    void OnSubMeshApply( wxCommandEvent &event ) override;

    void UndoMouseUp( wxMouseEvent &event ) override;
    void UndoKeyUp( wxKeyEvent &event ) override;
    void UndoKillFocus( wxFocusEvent &event ) override;

public:
    PbsParametersPanel( MainWindow *parent );

    void syncDatablockFromUI();
    void refreshFromDatablock();
    void refreshSubMeshList();
};

OGRE_ASSUME_NONNULL_END
