
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

#include "OgreHlmsPbsPrerequisites.h"

OGRE_ASSUME_NONNULL_BEGIN

class MainWindow;

class PbsTexturePanel final : public PbsTexturePanelBase
{
    MainWindow *m_mainWindow;

    Ogre::TextureGpu *m_reflectionMap;

    bool m_editing;
    bool m_ignoreUndo;
    /// wxWidgets emits UndoMouseUp() then OnSlider(). Thus if we set m_ignoreUndo = false in UndoMouseUp
    /// we'll push the current datablock.
    /// This doesn't happen with keyboard because it emits OnSlider() then UndoKeyUp().
    bool m_undoMouseUp;

    struct TextureUnit
    {
        wxButton   *mapButton;
        wxSpinCtrl *mapSpin;
    };

    struct DetailMapOffsetScale
    {
        SliderTextWidget x;
        SliderTextWidget y;
        SliderTextWidget w;
        SliderTextWidget h;
    };

    TextureUnit m_units[Ogre::NUM_PBSM_TEXTURE_TYPES];

    Ogre::PbsTextureTypes findFrom( wxButton *button ) const;

    wxChoice *ogre_nullable getBlendMode( const Ogre::PbsTextureTypes textureTypes );

    SliderTextWidget getStrengthSliderWidgets( const Ogre::PbsTextureTypes textureTypes );

    DetailMapOffsetScale getDetailMapOffsetScale( const Ogre::PbsTextureTypes textureTypes );

protected:
    // Handlers for PbsTexturePanelBase events.
    void OnTextureChangeButton( wxCommandEvent &event ) override;
    void OnSpinCtrl( wxSpinEvent &event ) override;
    void OnSlider( wxCommandEvent &event ) override;
    void OnText( wxCommandEvent &event ) override;
    void OnBlendModeChoice( wxCommandEvent &event ) override;
    void OnCollapsiblePaneChanged( wxCollapsiblePaneEvent &event ) override;

    void UndoMouseUp( wxMouseEvent &event ) override;
    void UndoKeyUp( wxKeyEvent &event ) override;
    void UndoKillFocus( wxFocusEvent &event ) override;

public:
    PbsTexturePanel( MainWindow *parent );

    void refreshFromDatablockAndApplyEnvMap();

    void notifyMeshChanged();
    void applyEnvMapToDatablock( Ogre::HlmsDatablock *baseDatablock );
    /// Needed when saving.
    void unsetEnvMapFromAllDatablocks();
};

OGRE_ASSUME_NONNULL_END
