
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

OGRE_ASSUME_NONNULL_BEGIN

class MainWindow;

class ProjectSettings final : public ProjectSettingsBase
{
    bool m_editing;

    wxString m_lastOpenDir;

    wxArrayString m_resources;
    wxString      m_relativeFolder;
    wxString      m_materialDstPath;
    wxString      m_projectPath;

protected:
    // Handlers for ProjectSettingsBase events.
    void OnResourcesAdd( wxCommandEvent &event ) override;
    void OnResourcesFolderAdd( wxCommandEvent &event ) override;
    void OnResourcesRemove( wxCommandEvent &event ) override;
    void OnText( wxCommandEvent &event ) override;
    void OnBrowseFolder( wxCommandEvent &event ) override;
    void OnBrowse( wxCommandEvent &event ) override;
    void OnButtonClick( wxCommandEvent &event ) override;

    void validateSettings();

    void loadProject( Ogre::HlmsManager *hlmsManager );

public:
    ProjectSettings( wxWindow *parent );

    int ShowModal() override;

    void newProject( Ogre::HlmsManager *hlmsManager );

    void openProject( wxString projectPath, Ogre::HlmsManager *hlmsManager );

    void openProject( Ogre::HlmsManager *hlmsManager );
};

OGRE_ASSUME_NONNULL_END
