
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

#include "OgreHlmsPbsPrerequisites.h"
#include "OgreHlmsSamplerblock.h"

OGRE_ASSUME_NONNULL_BEGIN

class ProjectSettings;

class SamplerSettings final : public SamplerSettingsBase
{
    ProjectSettings &m_projectSettings;

    bool m_editing;

protected:
    // Handlers for SamplerSettingsBase events.
    void OnPresetsChoice( wxCommandEvent &event ) override;
    void OnText( wxCommandEvent &event ) override;
    void OnFilterChoice( wxCommandEvent &event ) override;
    void OnAddressingModeChoice( wxCommandEvent &event ) override;
    void OnCompareFunctionChoice( wxCommandEvent &event ) override;

    void autogenName();

    bool hasAnisotropy() const;
    void validateAnisotropy();

    bool hasBorderColour() const;

    static Ogre::FilterOptions         getFilter( wxChoice *choice );
    static Ogre::TextureAddressingMode getAddressMode( wxChoice *choice );

    static void syncFilter( wxChoice *choice, Ogre::FilterOptions filter );
    static void syncAddressMode( wxChoice *choice, Ogre::TextureAddressingMode addressingMode );

    void refreshFromSamplerblock( const Ogre::HlmsSamplerblock &sampler,
                                  const bool                    bChangePreset = true );

public:
    SamplerSettings( wxWindow *parent, ProjectSettings &projectSettings,
                     const Ogre::HlmsSamplerblock &selectedSampler );

    Ogre::HlmsSamplerblock getSamplerblockFromUI() const;
};

OGRE_ASSUME_NONNULL_END
