
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

#include "OgreHlmsPbsPrerequisites.h"

OGRE_ASSUME_NONNULL_BEGIN

class MainWindow;

class SamplerSettingsBulkSelect final : public SamplerSettingsBulkSelectBase
{
    bool m_editing;

protected:
    void setupAllCheckboxes();

    void OnCheckbox( wxCommandEvent &event ) override;

public:
    SamplerSettingsBulkSelect( wxWindow *parent );

    bool isSelected( const Ogre::PbsTextureTypes textureTypes ) const;
};

OGRE_ASSUME_NONNULL_END
