
#pragma once

#include "Autogenerated/MaterialEditorBaseAutogen.h"

#include "MaterialEditorCommon.h"

OGRE_ASSUME_NONNULL_BEGIN

/** Implementing TextureSelectBase */
class TextureSelect : public TextureSelectBase
{
public:
    struct ResourceEntry
    {
        Ogre::String name;
        Ogre::String resourceGroup;
    };

private:
    bool                       m_editing;
    uint32_t                   m_chosenEntry;
    std::vector<ResourceEntry> m_resources;

    void saveSelection();

protected:
    void populateFromDatabase();

    // Handlers for TextureSelectBase events.
    void OnTextureSelect( wxCommandEvent &event );
    void OnSearchText( wxCommandEvent &event );
    void OnButtonClick( wxCommandEvent &event );

public:
    TextureSelect( wxWindow *parent );

    const ResourceEntry *ogre_nullable getChosenEntry() const;
};

OGRE_ASSUME_NONNULL_END
