
// This file has been auto-generated by clone_particle_systems.py
// Please DO NOT manually edit this file. Any subsequent invocation of
// clone_particle_systems.py will overwrite your modifications.
#include "OgreAreaEmitter2.h"
#include "OgreBoxEmitter2.h"
#include "OgreCylinderEmitter2.h"
#include "OgreEllipsoidEmitter2.h"
#include "OgreHollowEllipsoidEmitter2.h"
#include "OgrePointEmitter2.h"
#include "OgreRingEmitter2.h"
using namespace Ogre;
//-----------------------------------------------------------------------------
void AreaEmitter2::_cloneFrom( const EmitterDefData *_original )
{
    OGRE_ASSERT_HIGH( dynamic_cast<const AreaEmitter2 *>( _original ) );
    EmitterDefData::_cloneFrom( _original );
    const AreaEmitter2 *original = static_cast<const AreaEmitter2 *>( _original );
    this->mSize = original->mSize;
    this->mXRange = original->mXRange;
    this->mYRange = original->mYRange;
    this->mZRange = original->mZRange;
}

//-----------------------------------------------------------------------------
void HollowEllipsoidEmitter2::_cloneFrom( const EmitterDefData *_original )
{
    OGRE_ASSERT_HIGH( dynamic_cast<const HollowEllipsoidEmitter2 *>( _original ) );
    EllipsoidEmitter2::_cloneFrom( _original );
    const HollowEllipsoidEmitter2 *original = static_cast<const HollowEllipsoidEmitter2 *>( _original );
    this->mInnerSize = original->mInnerSize;
}

//-----------------------------------------------------------------------------
void RingEmitter2::_cloneFrom( const EmitterDefData *_original )
{
    OGRE_ASSERT_HIGH( dynamic_cast<const RingEmitter2 *>( _original ) );
    AreaEmitter2::_cloneFrom( _original );
    const RingEmitter2 *original = static_cast<const RingEmitter2 *>( _original );
    this->mInnerSizex = original->mInnerSizex;
    this->mInnerSizey = original->mInnerSizey;
}
