OGRE: Ogre::D3D11Mappings Class Reference
Ogre::D3D11Mappings Class Reference
#include <OgreD3D11Mappings.h>
Static Public Member Functions
static UINT _getAccessFlags (TextureUsage usage)
static UINT _getAccessFlags (v1::HardwareBuffer::Usage usage)
static PixelFormat _getClosestSupportedPF (PixelFormat ogrePF)
utility method, find closest Ogre pixel format that D3D11 can support
static DXGI_FORMAT _getGammaFormat (DXGI_FORMAT format, bool appendSRGB)
utility method, optionally maps plain format to _SRGB counterparts
static PixelFormat _getPF (DXGI_FORMAT d3dPF)
utility method, convert D3D11 pixel format to Ogre pixel format
static DXGI_FORMAT _getPF (PixelFormat ogrePF)
utility method, convert Ogre pixel format to D3D11 pixel format
static UINT _getTextureBindFlags (DXGI_FORMAT format, TextureUsage usage)
static UINT _getTextureMiscFlags (UINT bindflags, TextureType textype, TextureUsage usage)
static TextureType _getTexType (D3D11_SRV_DIMENSION type)
static D3D11_USAGE _getUsage (TextureUsage usage)
static D3D11_USAGE _getUsage (v1::HardwareBuffer::Usage usage)
static bool _isDynamic (TextureUsage usage)
static bool _isDynamic (v1::HardwareBuffer::Usage usage)
static D3D11_COMPARISON_FUNC get (CompareFunction cf)
return a D3D11 equivalent for a Ogre CompareFunction value
static void get (const ColourValue &inColour, float *outColour)
Get dx11 color.
static D3D11_FILTER get (const FilterOptions minification, const FilterOptions magnification, const FilterOptions mips, const bool comparison=false)
return a D3D11 state type for Ogre FilterOption min/mag/mip values
static D3D11_CULL_MODE get (CullingMode cm, bool flip=false)
return a D3D11 equivalent for a Ogre CillingMode value
static VertexElementSemantic get (LPCSTR sem)
static D3D11_FILL_MODE get (PolygonMode level)
return a D3D11 equivalent for a Ogre PolygonMode value
static D3D11_BLEND get (SceneBlendFactor sbf, bool forAlpha)
return a D3D11 equivalent for a Ogre SceneBlendFactor value
static D3D11_BLEND_OP get (SceneBlendOperation sbo)
return a D3D11 equivalent for a Ogre SceneBlendOperation value
static D3D11_STENCIL_OP get (StencilOperation op, bool invert=false)
return a D3D11 equivalent for a Ogre StencilOperation value
static D3D11_TEXTURE_ADDRESS_MODE get (TextureAddressingMode tam)
return a D3D11 equivalent for a Ogre TextureAddressingMode value
static D3D11_MAP get (v1::HardwareBuffer::LockOptions options, v1::HardwareBuffer::Usage usage)
Get lock options.
static LPCSTR get (VertexElementSemantic sem)
Get vertex semantic.
static DXGI_FORMAT get (VertexElementType vType)
Get vertex data type.
static DXGI_FORMAT getFormat (v1::HardwareIndexBuffer::IndexType itype)
Get index type.
static PixelBox getPixelBoxWithMapping (D3D11_BOX extents, DXGI_FORMAT pixelFormat, const D3D11_MAPPED_SUBRESOURCE &mapping)
utility method, generates Ogre PixelBox using usual parameters and dataPtr/rowPitch/slicePitch from D3D11_MAPPED_SUBRESOURCE
static void setPixelBoxMapping (PixelBox &box, const D3D11_MAPPED_SUBRESOURCE &mapping)
utility method, applies dataPtr/rowPitch/slicePitch from D3D11_MAPPED_SUBRESOURCE to Ogre PixelBox
Member Function Documentation
_getAccessFlags() [1/2]
static UINT Ogre::D3D11Mappings::_getAccessFlags (TextureUsage usage) inline static
References _getAccessFlags().
Referenced by _getAccessFlags().
_getAccessFlags() [2/2]
static UINT Ogre::D3D11Mappings::_getAccessFlags (v1::HardwareBuffer::Usage usage) static
_getClosestSupportedPF()
static PixelFormat Ogre::D3D11Mappings::_getClosestSupportedPF (PixelFormat ogrePF) static
utility method, find closest Ogre pixel format that D3D11 can support
_getGammaFormat()
static DXGI_FORMAT Ogre::D3D11Mappings::_getGammaFormat (DXGI_FORMAT format, bool appendSRGB) static
utility method, optionally maps plain format to _SRGB counterparts
_getPF() [1/2]
static PixelFormat Ogre::D3D11Mappings::_getPF (DXGI_FORMAT d3dPF) static
utility method, convert D3D11 pixel format to Ogre pixel format
_getPF() [2/2]
static DXGI_FORMAT Ogre::D3D11Mappings::_getPF (PixelFormat ogrePF) static
utility method, convert Ogre pixel format to D3D11 pixel format
_getTextureBindFlags()
static UINT Ogre::D3D11Mappings::_getTextureBindFlags (DXGI_FORMAT format, TextureUsage usage) static
_getTextureMiscFlags()
static UINT Ogre::D3D11Mappings::_getTextureMiscFlags (UINT bindflags, TextureType textype, TextureUsage usage) static
_getTexType()
static TextureType Ogre::D3D11Mappings::_getTexType (D3D11_SRV_DIMENSION type) static
_getUsage() [1/2]
static D3D11_USAGE Ogre::D3D11Mappings::_getUsage (TextureUsage usage) inline static
References _getUsage().
Referenced by _getUsage().
_getUsage() [2/2]
static D3D11_USAGE Ogre::D3D11Mappings::_getUsage (v1::HardwareBuffer::Usage usage) static
_isDynamic() [1/2]
static bool Ogre::D3D11Mappings::_isDynamic (TextureUsage usage) inline static
References _isDynamic().
Referenced by _isDynamic().
_isDynamic() [2/2]
static bool Ogre::D3D11Mappings::_isDynamic (v1::HardwareBuffer::Usage usage) static
get() [1/13]
static D3D11_COMPARISON_FUNC Ogre::D3D11Mappings::get (CompareFunction cf) static
return a D3D11 equivalent for a Ogre CompareFunction value
get() [2/13]
static void Ogre::D3D11Mappings::get (const ColourValue & inColour, float * outColour) static
Get dx11 color.
get() [3/13]
static D3D11_FILTER Ogre::D3D11Mappings::get (const FilterOptions minification, const FilterOptions magnification, const FilterOptions mips, const bool comparison = false) static
return a D3D11 state type for Ogre FilterOption min/mag/mip values
get() [4/13]
static D3D11_CULL_MODE Ogre::D3D11Mappings::get (CullingMode cm, bool flip = false) static
return a D3D11 equivalent for a Ogre CillingMode value
get() [5/13]
static VertexElementSemantic Ogre::D3D11Mappings::get (LPCSTR sem) static
get() [6/13]
static D3D11_FILL_MODE Ogre::D3D11Mappings::get (PolygonMode level) static
return a D3D11 equivalent for a Ogre PolygonMode value
get() [7/13]
static D3D11_BLEND Ogre::D3D11Mappings::get (SceneBlendFactor sbf, bool forAlpha) static
return a D3D11 equivalent for a Ogre SceneBlendFactor value
get() [8/13]
static D3D11_BLEND_OP Ogre::D3D11Mappings::get (SceneBlendOperation sbo) static
return a D3D11 equivalent for a Ogre SceneBlendOperation value
get() [9/13]
static D3D11_STENCIL_OP Ogre::D3D11Mappings::get (StencilOperation op, bool invert = false) static
return a D3D11 equivalent for a Ogre StencilOperation value
get() [10/13]
static D3D11_TEXTURE_ADDRESS_MODE Ogre::D3D11Mappings::get (TextureAddressingMode tam) static
return a D3D11 equivalent for a Ogre TextureAddressingMode value
get() [11/13]
static D3D11_MAP Ogre::D3D11Mappings::get (v1::HardwareBuffer::LockOptions options, v1::HardwareBuffer::Usage usage) static
Get lock options.
get() [12/13]
static LPCSTR Ogre::D3D11Mappings::get (VertexElementSemantic sem) static
Get vertex semantic.
get() [13/13]
static DXGI_FORMAT Ogre::D3D11Mappings::get (VertexElementType vType) static
Get vertex data type.
getFormat()
static DXGI_FORMAT Ogre::D3D11Mappings::getFormat (v1::HardwareIndexBuffer::IndexType itype) static
Get index type.
getPixelBoxWithMapping()
static PixelBox Ogre::D3D11Mappings::getPixelBoxWithMapping (D3D11_BOX extents, DXGI_FORMAT pixelFormat, const D3D11_MAPPED_SUBRESOURCE & mapping) static
utility method, generates Ogre PixelBox using usual parameters and dataPtr/rowPitch/slicePitch from D3D11_MAPPED_SUBRESOURCE
setPixelBoxMapping()
static void Ogre::D3D11Mappings::setPixelBoxMapping (PixelBox & box, const D3D11_MAPPED_SUBRESOURCE & mapping) static
utility method, applies dataPtr/rowPitch/slicePitch from D3D11_MAPPED_SUBRESOURCE to Ogre PixelBox
The documentation for this class was generated from the following file:
OgreD3D11Mappings.h