OGRE: Ogre::ConstMapRange< T > Struct Template Reference
Ogre::ConstMapRange< T > Struct Template Reference
Predefined type.
#include <OgreIteratorRange.h>
Public Types
typedef T const_iterator
typedef to fulfill container interface
typedef T iterator
typedef to fulfill container interface
typedef iterator_range< T > type
defines the real used type
Public Member Functions
ConstMapRange (const MapRange< T > &rhs)
Constructor.
ConstMapRange (const T &c)
Constructor.
ConstMapRange (typename T::const_iterator b, typename T::const_iterator e)
Constructor.
ConstMapRange (typename T::iterator b, typename T::iterator e)
Constructor.
T begin () const
access to the begin of the range
bool empty () const
informs if there are any elements in the range
T end () const
access to the end of the range
bool equal (const iterator_range &other) const
comparison for equality
bool operator!= (const ConstMapRange &rhs) const
comparison operator for inequality
bool operator!= (const iterator_range &rhs) const
comparison operator for inequality
bool operator== (const ConstMapRange &rhs) const
comparison operator for equality
bool operator== (const iterator_range &rhs) const
comparison operator for equality
Detailed Description
template<typename T>
struct Ogre::ConstMapRange< T >
Predefined type.
Template Parameters
T iterator type
compatility class for ConstMapIterator
Member Typedef Documentation
const_iterator
template<typename T > typedef T Ogre::iterator_range< T >::const_iterator inherited
typedef to fulfill container interface
Note
there is no distinction between const_iterator and iterator.
iterator
template<typename T > typedef T Ogre::iterator_range< T >::iterator inherited
typedef to fulfill container interface
Note
there is no distinction between const_iterator and iterator.
type
template<typename T > typedef iterator_range<T> Ogre::iterator_range< T >::type inherited
defines the real used type
type will be defined as Ogre::iterator_range if not used with boost
otherwise the type will be boost::iterator_range
Constructor & Destructor Documentation
ConstMapRange() [1/4]
template<typename T > Ogre::ConstMapRange< T >::ConstMapRange (const T & c) inline
Constructor.
Remarks
Provide a container to initialise.
ConstMapRange() [2/4]
template<typename T > Ogre::ConstMapRange< T >::ConstMapRange (typename T::iterator b, typename T::iterator e) inline
Constructor.
Remarks
Provide a start and end iterator to initialise.
ConstMapRange() [3/4]
template<typename T > Ogre::ConstMapRange< T >::ConstMapRange (typename T::const_iterator b, typename T::const_iterator e) inline
Constructor.
Remarks
Provide a start and end const_iterator to initialise.
ConstMapRange() [4/4]
template<typename T > Ogre::ConstMapRange< T >::ConstMapRange (const MapRange< T > & rhs) inline
Constructor.
Remarks
Provide a MapRange to initialise.
Member Function Documentation
begin()
template<typename T > T Ogre::iterator_range< T >::begin () const inline inherited
access to the begin of the range
empty()
template<typename T > bool Ogre::iterator_range< T >::empty () const inline inherited
informs if there are any elements in the range
end()
template<typename T > T Ogre::iterator_range< T >::end () const inline inherited
access to the end of the range
equal()
template<typename T > bool Ogre::iterator_range< T >::equal (const iterator_range< T > & other) const inline inherited
comparison for equality
Referenced by Ogre::ConstMapRange< T >::operator!=(), Ogre::ConstVectorRange< T >::operator!=(), Ogre::MapRange< T >::operator!=(), Ogre::VectorRange< T >::operator!=(), Ogre::ConstMapRange< T >::operator==(), Ogre::ConstVectorRange< T >::operator==(), Ogre::iterator_range< T >::operator==(), Ogre::MapRange< T >::operator==(), and Ogre::VectorRange< T >::operator==().
operator!=() [1/2]
template<typename T > bool Ogre::ConstMapRange< T >::operator!= (const ConstMapRange< T > & rhs) const inline
comparison operator for inequality
References Ogre::iterator_range< T >::equal().
operator!=() [2/2]
template<typename T > bool Ogre::iterator_range< T >::operator!= (const iterator_range< T > & rhs) const inline inherited
comparison operator for inequality
References Ogre::iterator_range< T >::operator==().
operator==() [1/2]
template<typename T > bool Ogre::ConstMapRange< T >::operator== (const ConstMapRange< T > & rhs) const inline
comparison operator for equality
References Ogre::iterator_range< T >::equal().
operator==() [2/2]
template<typename T > bool Ogre::iterator_range< T >::operator== (const iterator_range< T > & rhs) const inline inherited
comparison operator for equality
References Ogre::iterator_range< T >::equal().
Referenced by Ogre::iterator_range< T >::operator!=().
The documentation for this struct was generated from the following file:
OgreIteratorRange.h